# Generated by Django 6.0 on 2025-12-30 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tenant_country_tenant_description_tenant_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('Comunicado', 'Comunicado'), ('Jogo', 'Jogo'), ('Transferência', 'Transferência'), ('Clube', 'Clube'), ('Entrevista', 'Entrevista')], default='Comunicado', max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.tenant')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
