# Generated by Django 6.0 on 2026-01-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_likes_newsarticle_shares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('Comunicado', 'Comunicado'), ('Jogo', 'Jogo'), ('Transferência', 'Transferência'), ('Clube', 'Clube'), ('Entrevista', 'Entrevista'), ('Notícias', 'Notícias'), ('Outros', 'Outros')], default='Comunicado', max_length=50),
        ),
    ]
