# Generated by Django 5.2.6 on 2026-06-28 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("federation", "Federação"),
                            ("association", "Associação"),
                            ("league", "Liga"),
                            ("organizer", "Organizador"),
                            ("academy", "Academia"),
                        ],
                        default="federation",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'faf' for faf.bolayetu.com",
                        max_length=63,
                        null=True,
                        unique=True,
                        verbose_name="Subdomain",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#014D40", max_length=7, verbose_name="Primary Color"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#94D3C1", max_length=7, verbose_name="Secondary Color"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Angola", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="City"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "language",
                    models.CharField(
                        default="pt", max_length=5, verbose_name="Language"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Luanda", max_length=50, verbose_name="Timezone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("active", "Ativa"),
                            ("suspended", "Suspensa"),
                            ("closed", "Encerrada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Is Public"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["name"],
            },
        ),
    ]
