# Generated by Django 6.0 on 2025-12-19 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('primary_color', models.CharField(default='#22c55e', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
