# Generated by Django 5.2.6 on 2026-06-27 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("federation", "Federação"),
                            ("association", "Associação"),
                            ("club", "Clube"),
                            ("academy", "Academia"),
                        ],
                        default="federation",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="tenants/logos/"
                    ),
                ),
                ("primary_color", models.CharField(default="#014D40", max_length=7)),
                ("secondary_color", models.CharField(default="#94D3C1", max_length=7)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("country", models.CharField(default="Angola", max_length=100)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "subdomain",
                    models.CharField(blank=True, max_length=63, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
