# Generated by Django 4.2.26 on 2026-06-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.URLField(blank=True, help_text='Cloudflare R2 URL for the organization logo.', max_length=500, null=True, verbose_name='Logo URL'),
        ),
    ]
