# Generated by Django 5.2.6 on 2026-06-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="banner",
            field=models.URLField(
                blank=True,
                help_text="Cloudflare R2 URL for the organization banner image.",
                max_length=500,
                null=True,
                verbose_name="Banner URL",
            ),
        ),
    ]
