# Generated by Django 6.0 on 2026-01-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_country_tenant_description_tenant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('league', 'League'), ('federation', 'Federation'), ('association', 'Association'), ('tournament', 'Tournament'), ('school', 'School'), ('amateur', 'Amateur')], default='league', max_length=20),
        ),
    ]
