# Generated by Django 6.0 on 2026-06-26 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_tenant_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["name"],
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
            },
        ),
        migrations.AddField(
            model_name="tenant",
            name="accent_color",
            field=models.CharField(
                default="#E63946", max_length=7, verbose_name="Accent colour"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive tenants are not resolved by TenantMiddleware",
                verbose_name="Is active",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="country",
            field=models.CharField(
                blank=True, default="Angola", max_length=100, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Public tenants appear on the platform directory",
                verbose_name="Is public",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="tenants/logos/", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="primary_color",
            field=models.CharField(
                default="#1B4D3E", max_length=7, verbose_name="Primary colour"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(
                default="#D4AF37", max_length=7, verbose_name="Secondary colour"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(
                help_text="Used as subdomain: slug.bolayetu.com",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="type",
            field=models.CharField(
                choices=[
                    ("federation", "Federation"),
                    ("league", "League"),
                    ("association", "Association"),
                    ("tournament", "Tournament organiser"),
                    ("school", "Football School"),
                    ("amateur", "Amateur Organisation"),
                ],
                default="league",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Verified by Bolayetu platform administrators",
                verbose_name="Verified",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="website",
            field=models.URLField(blank=True, default="", verbose_name="Website"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="tenant_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["is_active", "is_public"], name="tenant_status_idx"
            ),
        ),
    ]
