# Generated by Django 6.0 on 2026-06-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tenant_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Organization banner file (stored in configured DEFAULT_FILE_STORAGE).",
                max_length=500,
                null=True,
                upload_to="banners/",
                verbose_name="Banner",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Organization logo file (stored in configured DEFAULT_FILE_STORAGE).",
                max_length=500,
                null=True,
                upload_to="logos/",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="type",
            field=models.CharField(
                choices=[
                    ("federation", "Federação"),
                    ("association", "Associação"),
                    ("league", "Liga"),
                    ("organizer", "Organizador"),
                    ("academy", "Academia"),
                    ("club", "Clube"),
                    ("player", "Jogador"),
                ],
                default="federation",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
