# Generated by Django 6.0 on 2026-07-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tenant_banner_alter_tenant_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='banner',
            field=models.ImageField(blank=True, editable=False, help_text='Deprecated legacy field. Use MediaAsset/MediaUsage (role=banner) instead.', max_length=500, null=True, upload_to='banners/', verbose_name='Banner (deprecated)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, editable=False, help_text='Deprecated legacy field. Use MediaAsset/MediaUsage (role=logo) instead.', max_length=500, null=True, upload_to='logos/', verbose_name='Logo (deprecated)'),
        ),
    ]
