# Generated by Django 6.0 on 2026-07-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_tenant_banner_alter_tenant_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="logo",
        ),
    ]
