# Generated by Django 6.0 on 2026-07-06 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0006_remove_tenant_banner_remove_tenant_logo"),
        ("media_assets", "0002_alter_mediaasset_owner_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Report Name")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("club_overview", "Club Overview"),
                            ("competition_summary", "Competition Summary"),
                            (
                                "organization_performance",
                                "Organization Performance Summary",
                            ),
                            ("financial_summary", "Financial Summary"),
                        ],
                        max_length=50,
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel (XLSX)"),
                            ("pdf", "PDF"),
                        ],
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Query Filters"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="media_assets.mediaasset",
                        verbose_name="Report File",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Report",
                "verbose_name_plural": "Generated Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPISnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("date", models.DateField(verbose_name="Snapshot Date")),
                (
                    "metric_key",
                    models.CharField(
                        choices=[
                            ("total_clubs", "Total Clubs"),
                            ("total_players", "Total Players"),
                            ("active_tournaments", "Active Tournaments"),
                            ("total_matches", "Total Matches"),
                            ("matches_finished", "Matches Finished"),
                            ("matches_scheduled", "Matches Scheduled"),
                            ("matches_live", "Matches Live"),
                            ("goals_total", "Goals Total"),
                            ("avg_goals_per_match", "Average Goals Per Match"),
                            ("organization_subscribers", "Organization Subscribers"),
                            ("total_revenue", "Total Revenue"),
                            ("players_this_month", "Players Joined This Month"),
                            ("players_last_month", "Players Joined Last Month"),
                        ],
                        max_length=100,
                        verbose_name="Metric Key",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Metric Value")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_snapshots",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Snapshot",
                "verbose_name_plural": "KPI Snapshots",
                "ordering": ["-date", "metric_key"],
                "unique_together": {("tenant", "date", "metric_key")},
            },
        ),
    ]
