# Generated by Django 6.0 on 2025-12-22 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0002_clubhistory'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Em andamento'), ('upcoming', 'Inscrições'), ('completed', 'Terminado')], default='upcoming', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('max_teams', models.IntegerField(default=16)),
                ('type', models.CharField(choices=[('League', 'Liga (Pontos corridos)'), ('Knockout', 'Eliminatória'), ('Groups', 'Fase de Grupos + Eliminatória')], default='League', max_length=50)),
                ('clubs', models.ManyToManyField(blank=True, related_name='tournaments', to='clubes.club')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
