# Generated by Django 6.0 on 2025-12-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('League', 'Liga (Pontos corridos)'), ('Knockout', 'Eliminatória'), ('Groups', 'Fase de Grupos + Eliminatória')], default='Liga', max_length=50),
        ),
    ]
