# Generated by Django 6.0 on 2025-12-23 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_clubhistory'),
        ('core', '0001_initial'),
        ('torneios', '0002_alter_tournament_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('clubs', models.ManyToManyField(blank=True, related_name='tournament_groups', to='clubes.club')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_groups', to='core.tenant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='torneios.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
