# Generated by Django 6.0 on 2025-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0003_tournamentgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('League', 'Liga (Pontos corridos)'), ('Knockout', 'Mata-Mata'), ('Groups', 'Fase de Grupos + Eliminatória')], default='League', max_length=50),
        ),
    ]
