# Generated by Django 6.0 on 2026-01-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0005_tournament_champions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
