# Generated by Django 6.0 on 2026-06-26 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneios", "0006_tournament_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournament",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tournamentgroup",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="tournament",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="tournamentgroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="tournamentgroup",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="tournamentgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
