"""
BOLAYETU — MatchReport Model

Represents a generated match report (PDF or structured data).

Architecture:
    - MatchReport is tenant-scoped
    - Stores both structured data (JSON) and PDF reference
    - Links to MediaAsset for PDF storage via DAM
    - Tracks generation status and timestamps
"""

from django.db import models
from django.utils import timezone
from common.models import BaseModel


class MatchReport(BaseModel):
    """
    Represents a generated match report.
    
    Contains structured data (JSON) and optional PDF file stored in DAM.
    Reports can be generated automatically after match completion
    or manually requested.
    """

    class ReportStatus(models.TextChoices):
        PENDING = "pending", "Pendente"
        GENERATING = "generating", "A Gerar"
        COMPLETED = "completed", "Concluído"
        FINALIZED = "finalized", "Finalizado"
        FAILED = "failed", "Falhou"

    class ReportType(models.TextChoices):
        FULL = "full", "Relatório Completo"
        SUMMARY = "summary", "Resumo"
        STATISTICS = "statistics", "Estatísticas"
        EVENTS = "events", "Eventos"
        OFFICIAL = "official", "Relatório Oficial (Súmula)"

    # ─── Core Relations ─────────────────────────────────────────────────────
    match = models.OneToOneField(
        "competitions.Match",
        on_delete=models.CASCADE,
        related_name="match_report",
        verbose_name="Match",
    )

    # ─── Score ──────────────────────────────────────────────────────────────
    home_score = models.PositiveSmallIntegerField(
        default=0,
        verbose_name="Home Score",
    )
    away_score = models.PositiveSmallIntegerField(
        default=0,
        verbose_name="Away Score",
    )
    home_goals_against = models.PositiveSmallIntegerField(
        default=0,
        verbose_name="Home Goals Against",
    )
    away_goals_against = models.PositiveSmallIntegerField(
        default=0,
        verbose_name="Away Goals Against",
    )

    # ─── Report Details ──────────────────────────────────────────────────────
    report_type = models.CharField(
        max_length=20,
        choices=ReportType.choices,
        default=ReportType.FULL,
        verbose_name="Report Type",
    )
    status = models.CharField(
        max_length=20,
        choices=ReportStatus.choices,
        default=ReportStatus.PENDING,
        verbose_name="Status",
    )

    # ─── Match Duration ──────────────────────────────────────────────────────
    match_duration = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Match Duration (minutes)",
    )

    # ─── Structured Data ─────────────────────────────────────────────────────
    data = models.JSONField(
        default=dict,
        blank=True,
        verbose_name="Report Data",
        help_text="Structured report data (JSON).",
    )

    # ─── PDF Storage ─────────────────────────────────────────────────────────
    pdf_asset = models.ForeignKey(
        "media_assets.MediaAsset",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="match_reports",
        verbose_name="PDF Asset",
        help_text="PDF file stored in DAM.",
    )
    pdf_url = models.URLField(
        max_length=2000,
        blank=True,
        verbose_name="PDF URL",
        help_text="Direct URL to PDF (if generated).",
    )

    # ─── Generation Tracking ──────────────────────────────────────────────────
    generated_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="Generated At",
    )
    generated_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="match_reports_generated",
        verbose_name="Generated By",
    )

    # ─── Task Tracking ────────────────────────────────────────────────────────
    task_id = models.CharField(
        max_length=255,
        blank=True,
        default="",
        verbose_name="Task ID",
        help_text="Celery task ID for async generation.",
    )

    # ─── Error Handling ───────────────────────────────────────────────────────
    error_message = models.TextField(
        blank=True,
        default="",
        verbose_name="Error Message",
    )

    # ─── Audit ────────────────────────────────────────────────────────────────
    requested_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Requested At",
    )
    requested_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="match_reports_requested",
        verbose_name="Requested By",
    )

    finalized_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="Finalized At",
    )
    finalized_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="match_reports_finalized",
        verbose_name="Finalized By",
    )

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Match Report"
        verbose_name_plural = "Match Reports"
        indexes = [
            models.Index(fields=["match", "report_type"]),
            models.Index(fields=["status"]),
        ]

    def __str__(self) -> str:
        return f"[{self.match}] {self.home_score}-{self.away_score} ({self.get_status_display()})"

    @property
    def is_completed(self) -> bool:
        """Check if report generation is completed."""
        return self.status == self.ReportStatus.COMPLETED

    @property
    def is_finalized(self) -> bool:
        """Check if report is finalized."""
        return self.status == self.ReportStatus.FINALIZED

    @property
    def is_failed(self) -> bool:
        """Check if report generation failed."""
        return self.status == self.ReportStatus.FAILED

    @property
    def has_pdf(self) -> bool:
        """Check if PDF is available."""
        return bool(self.pdf_asset or self.pdf_url)

    def mark_generating(self, task_id: str = "") -> None:
        """Mark report as generating."""
        self.status = self.ReportStatus.GENERATING
        self.task_id = task_id
        self.save(update_fields=["status", "task_id", "updated_at"])

    def mark_completed(self, pdf_asset=None, pdf_url: str = "") -> None:
        """Mark report as completed."""
        self.status = self.ReportStatus.COMPLETED
        self.generated_at = timezone.now()
        if pdf_asset:
            self.pdf_asset = pdf_asset
        if pdf_url:
            self.pdf_url = pdf_url
        self.save(update_fields=["status", "generated_at", "pdf_asset", "pdf_url", "updated_at"])

    def mark_failed(self, error_message: str = "") -> None:
        """Mark report as failed."""
        self.status = self.ReportStatus.FAILED
        self.error_message = error_message
        self.save(update_fields=["status", "error_message", "updated_at"])

    def finalize(self, user) -> None:
        """Finalize the match report."""
        self.status = self.ReportStatus.FINALIZED
        self.finalized_at = timezone.now()
        self.finalized_by = user
        self.save(update_fields=["status", "finalized_at", "finalized_by", "updated_at"])


class Goal(BaseModel):
    """
    Represents a goal scored in a match.
    
    Records player, club, minute, and type of goal.
    """

    class GoalType(models.TextChoices):
        NORMAL = "normal", "Normal"
        PENALTY = "penalty", "Penalty"
        OWN_GOAL = "own_goal", "Own Goal"

    match = models.ForeignKey(
        "competitions.Match",
        on_delete=models.CASCADE,
        related_name="goals",
        verbose_name="Match",
    )
    player = models.ForeignKey(
        "players.Player",
        on_delete=models.CASCADE,
        related_name="goals",
        verbose_name="Player",
    )
    club = models.ForeignKey(
        "clubs.Club",
        on_delete=models.CASCADE,
        related_name="goals",
        verbose_name="Club",
    )
    minute = models.PositiveSmallIntegerField(
        verbose_name="Minute",
        help_text="Minute when goal was scored (1-180).",
    )
    goal_type = models.CharField(
        max_length=20,
        choices=GoalType.choices,
        default=GoalType.NORMAL,
        verbose_name="Goal Type",
    )
    assist_player = models.ForeignKey(
        "players.Player",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assists",
        verbose_name="Assist Player",
    )

    class Meta:
        ordering = ["match", "minute"]
        verbose_name = "Goal"
        verbose_name_plural = "Goals"
        indexes = [
            models.Index(fields=["match", "minute"]),
            models.Index(fields=["player", "match"]),
        ]

    def __str__(self) -> str:
        return f"[{self.match}] {self.player.full_name} ({self.minute}') - {self.get_goal_type_display()}"


class MatchStats(BaseModel):
    """
    Represents match statistics for a team in a match.
    
    Stores possession, shots, passes, fouls, cards, etc.
    """

    match = models.ForeignKey(
        "competitions.Match",
        on_delete=models.CASCADE,
        related_name="matchstats_set",
        verbose_name="Match",
    )
    club = models.ForeignKey(
        "clubs.Club",
        on_delete=models.CASCADE,
        related_name="match_stats",
        verbose_name="Club",
    )

    # ─── Possession & Passing ──────────────────────────────────────────────
    possession = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Ball Possession %",
        help_text="Percentage of ball possession (0-100).",
    )
    shots_on_goal = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Shots on Goal",
    )
    shots_off_goal = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Shots off Goal",
    )
    passes = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Total Passes",
    )
    passes_accuracy = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Pass Accuracy %",
        help_text="Percentage of accurate passes (0-100).",
    )

    # ─── Disciplinary ──────────────────────────────────────────────────────
    fouls = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Fouls Committed",
    )
    yellow_cards = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Yellow Cards",
    )
    red_cards = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Red Cards",
    )

    # ─── Opportunities ────────────────────────────────────────────────────
    corner_kicks = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Corner Kicks",
    )

    class Meta:
        ordering = ["match", "club"]
        verbose_name = "Match Statistic"
        verbose_name_plural = "Match Statistics"
        constraints = [
            models.UniqueConstraint(
                fields=["match", "club"],
                name="unique_match_club_stats",
            ),
        ]
        indexes = [
            models.Index(fields=["match", "club"]),
        ]

    def __str__(self) -> str:
        return f"[{self.match}] {self.club.name} Stats"

