# Generated by Django 6.0 on 2026-01-08 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0004_alter_club_stadium_name'),
        ('core', '0003_alter_tenant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='active_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='clubes.club')),
                ('tenant', models.ForeignKey(help_text='A organização à qual esta staff pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Membro da Equipa Técnica',
                'verbose_name_plural': 'Membros da Equipa Técnica',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name', 'club')},
            },
        ),
    ]
