# Generated by Django 6.0 on 2026-06-21 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("clubes", "0007_club_organizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="clube_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_club",
                to="accounts.clubeprofile",
            ),
        ),
    ]
