# Generated by Django 6.0 on 2026-01-23 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0006_club_short_fields'),
        ('core', '0003_alter_tenant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='treinadores/')),
                ('estilo_jogo', models.TextField()),
                ('biografia', models.TextField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinadores', to='core.tenant')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LicencaTreinador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('entidade', models.CharField(max_length=100)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='treinadores.treinador')),
            ],
            options={
                'ordering': ['-data_emissao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTreinador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.CharField(choices=[('Treinador Principal', 'Treinador Principal'), ('Treinador Adjunto', 'Treinador Adjunto'), ('Treinador Interino', 'Treinador Interino'), ('Preparador Físico', 'Preparador Físico'), ('Treinador de Guarda-Redes', 'Treinador de Guarda-Redes'), ('Analista', 'Analista'), ('Outro', 'Outro')], default='Treinador Principal', max_length=50)),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('jogos', models.PositiveIntegerField(default=0)),
                ('vitorias', models.PositiveIntegerField(default=0)),
                ('empates', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('conquistas', models.TextField(blank=True, default='')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_treinadores', to='clubs.club')),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='treinadores.treinador')),
            ],
            options={
                'ordering': ['-data_inicio', '-created_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('data_fim__isnull', True)), fields=('treinador',), name='unique_current_club_per_treinador')],
            },
        ),
    ]
