# Generated by Django 6.0 on 2025-12-21 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_clubhistory'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(default='Angolana', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_starter', models.BooleanField(default=False)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='clubs.club')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
