# Generated by Django 6.0 on 2025-12-22 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='foot',
            field=models.CharField(choices=[('Direito', 'Direito'), ('Esquerdo', 'Esquerdo'), ('Ambidestro', 'Ambidestro')], default='Direito', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('injured', 'Lesionado'), ('suspended', 'Suspenso')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, help_text='kg', null=True),
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=255)),
                ('matches', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='jogadores.player')),
            ],
            options={
                'ordering': ['-season'],
            },
        ),
    ]
