# Generated by Django 6.0 on 2025-12-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_clubhistory'),
        ('jogadores', '0002_player_date_of_birth_player_foot_player_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_players', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='is_trophy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='placement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('injured', 'Lesionado'), ('suspended', 'Suspenso')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_history', to='clubes.club'),
        ),
    ]
