# Generated by Django 6.0 on 2025-12-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0003_player_last_club_playerhistory_is_trophy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Avançado', 'Avançado'), ('Meio-campo', 'Meio-campo'), ('Defesa', 'Defesa'), ('Guarda-Redes', 'Guarda Redes')], default='Avançado', max_length=50),
        ),
    ]
