# Generated by Django 6.0 on 2025-12-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0004_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
    ]
