# Generated by Django 6.0 on 2026-01-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0005_playerhistory_minutes_playerhistory_red_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Avançado', 'Avançado'), ('Extremo-direito', 'Extremo Direito'), ('Extremo-esquerdo', 'Extremo Esquerdo'), ('Meio-campo', 'Meio-campo'), ('Médio-direito', 'Médio Direito'), ('Médio-esquerdo', 'Médio Esquerdo'), ('Defesa-central', 'Defesa Central'), ('Lateral-esquerdo', 'Lateral Esquerdo'), ('Lateral-direito', 'Lateral Direito'), ('Guarda-Redes', 'Guarda Redes')], default='Avançado', max_length=50),
        ),
    ]
