# Generated by Django 6.0 on 2026-01-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_club_short_fields'),
        ('core', '0003_alter_tenant_type'),
        ('jogadores', '0007_player_shirt_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('club', 'number'), name='unique_player_number_per_club'),
        ),
    ]
