# Generated by Django 6.0 on 2026-06-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("jogadores", "0008_player_unique_player_number_per_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="clube_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="associated_players",
                to="accounts.clubeprofile",
            ),
        ),
    ]
