# Generated by Django 6.0 on 2026-06-21 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("jogadores", "0009_player_clube_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="jogador_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="athlete",
                to="accounts.jogadorprofile",
            ),
        ),
    ]
