# Generated by Django 6.0 on 2026-06-21 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubeProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("sigla", models.CharField(blank=True, max_length=50)),
                ("fundacao", models.DateField(blank=True, null=True)),
                ("historia", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="clubs/logos/"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="clubs/banners/"
                    ),
                ),
                ("estadio", models.CharField(blank=True, max_length=255)),
                ("cores", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clube_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Clube",
                "verbose_name_plural": "Perfis de Clubs",
            },
        ),
        migrations.CreateModel(
            name="JogadorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome_completo", models.CharField(max_length=255)),
                ("nome_desportivo", models.CharField(blank=True, max_length=255)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("nacionalidade", models.CharField(blank=True, max_length=100)),
                (
                    "altura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("pe_preferencial", models.CharField(blank=True, max_length=20)),
                ("posicao", models.CharField(blank=True, max_length=100)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="jogadores/fotos/"
                    ),
                ),
                ("biografia", models.TextField(blank=True)),
                ("agente", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogador_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Jogador",
                "verbose_name_plural": "Perfis de Jogadores",
            },
        ),
        migrations.CreateModel(
            name="AdeptoProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="adeptos/fotos/"
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("pais", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adepto_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clubs_favoritos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seguidores",
                        to="accounts.clubeprofile",
                    ),
                ),
                (
                    "jogadores_favoritos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seguidores",
                        to="accounts.jogadorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Adepto",
                "verbose_name_plural": "Perfis de Adeptos",
            },
        ),
        migrations.CreateModel(
            name="OrganizacaoProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("sigla", models.CharField(blank=True, max_length=50)),
                ("descricao", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("pais", models.CharField(blank=True, max_length=100)),
                ("provincia", models.CharField(blank=True, max_length=100)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizacoes/logos/"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizacoes/banners/"
                    ),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizacao_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Organização",
                "verbose_name_plural": "Perfis de Organizações",
            },
        ),
    ]
