# Generated by Django 6.0 on 2026-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('admin', 'Platform Admin'), ('organization', 'Organization'), ('club', 'Club'), ('player', 'Player'), ('fan', 'Fan')], default='fan', help_text='Primary self-service profile for the account.', max_length=30, verbose_name='Profile Type'),
        ),
    ]
