# Generated by Django 6.0 on 2025-12-21 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0002_clubhistory'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('stadium', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('live', 'Ao Vivo'), ('finished', 'Terminado'), ('postponed', 'Adiado')], default='scheduled', max_length=20)),
                ('round', models.CharField(blank=True, max_length=100)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='clubes.club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='clubes.club')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
