# Generated by Django 6.0 on 2025-12-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_match_venue'),
        ('torneios', '0002_alter_tournament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='torneios.tournament'),
        ),
    ]
