# Generated by Django 6.0 on 2025-12-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_match_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='stadium',
        ),
    ]
