# Generated by Django 6.0 on 2025-12-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0004_remove_match_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_period',
            field=models.CharField(blank=True, choices=[('1H', '1ª Parte'), ('HT', 'Intervalo'), ('2H', '2ª Parte'), ('FT', 'Terminado')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='extra_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='period_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
