# Generated by Django 6.0 on 2026-01-13 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitros', '0001_initial'),
        ('partidas', '0005_match_current_period_match_extra_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='arbitros.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='assistant_referees',
            field=models.ManyToManyField(blank=True, related_name='assistant_matches', to='arbitros.referee'),
        ),
    ]

