# Generated by Django 6.0 on 2026-01-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0006_match_referees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='assistant_referees',
        ),
        migrations.RemoveField(
            model_name='match',
            name='referee',
        ),
    ]
