# Generated by Django 6.0 on 2026-01-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitros', '0001_initial'),
        ('partidas', '0007_remove_match_assistant_referees_remove_match_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='assistant_referees',
            field=models.ManyToManyField(blank=True, related_name='assistant_matches', to='arbitros.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='arbitros.referee'),
        ),
    ]
