# Generated by Django 6.0 on 2026-01-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0008_match_assistant_referees_match_referee'),
        ('treinadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='treinadores.treinador'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='treinadores.treinador'),
        ),
    ]
