# Generated by Django 6.0 on 2026-01-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0009_match_away_coach_match_home_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stats_processed',
            field=models.BooleanField(default=False),
        ),
    ]
