# Generated by Django 6.0 on 2026-06-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_rbac_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("ORGANIZACAO", "Organização"),
                    ("CLUBE", "Clube"),
                    ("JOGADOR", "Jogador"),
                    ("ADEPTO", "Adepto"),
                    ("superadmin", "Super Admin"),
                    ("ads_manager", "Ads Manager"),
                    ("admin", "Tenant Admin"),
                    ("manager", "Manager"),
                    ("viewer", "Viewer"),
                ],
                default="ADEPTO",
                max_length=20,
            ),
        ),
    ]
