# Generated by Django 6.0 on 2026-01-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
