# Generated by Django 6.0 on 2026-01-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_subscriptionplan_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_news_articles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
