# Generated by Django 6.0 on 2026-01-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0004_alter_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('freemium', 'Freemium'), ('basic', 'Basic'), ('pro', 'Professional'), ('premium', 'Premium'), ('advanced', 'Advanced')], max_length=20),
        ),
    ]
