# Generated by Django 6.0 on 2026-01-04 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_tenant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_alerts', models.BooleanField(default=True)),
                ('match_updates', models.BooleanField(default=True)),
                ('marketing', models.BooleanField(default=False)),
                ('financial_reports', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
