# Generated by Django 6.0 on 2026-07-01 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_alter_tenant_banner_alter_tenant_logo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this asset (e.g. 'FAF Logo 2025').",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, verbose_name="Slug"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Imagem"),
                            ("video", "Vídeo"),
                            ("document", "Documento"),
                            ("audio", "Áudio"),
                            ("pdf", "PDF"),
                            ("archive", "Arquivo"),
                        ],
                        default="image",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("logo", "Logótipo"),
                            ("banner", "Banner"),
                            ("cover", "Capa"),
                            ("gallery", "Galeria"),
                            ("video", "Vídeo"),
                            ("document", "Documento"),
                            ("certificate", "Certificado"),
                            ("report", "Relatório"),
                            ("export", "Exportação"),
                            ("news_image", "Imagem de Notícia"),
                            ("sponsor_logo", "Logótipo de Patrocinador"),
                        ],
                        default="logo",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="The name of the file as provided by the user.",
                        max_length=500,
                        verbose_name="Original Filename",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="e.g. image/jpeg, image/png, application/pdf",
                        max_length=100,
                        verbose_name="MIME Type",
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        help_text="File extension without dot (e.g. 'jpg', 'png', 'pdf').",
                        max_length=20,
                        verbose_name="Extension",
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        help_text="File size in bytes.", verbose_name="Size (bytes)"
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the file content for integrity verification.",
                        max_length=64,
                        verbose_name="SHA-256 Checksum",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Width (px)"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Height (px)"
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        blank=True,
                        help_text="Storage bucket name (e.g. bolayetu-storage).",
                        max_length=255,
                        verbose_name="Bucket",
                    ),
                ),
                (
                    "object_key",
                    models.CharField(
                        help_text="The path/key within the bucket (e.g. tenant/faf/logos/uuid.jpg).",
                        max_length=1000,
                        verbose_name="Object Key",
                    ),
                ),
                (
                    "cdn_url",
                    models.URLField(
                        blank=True,
                        help_text="Public CDN URL for this asset (Cloudflare CDN or local).",
                        max_length=2000,
                        verbose_name="CDN URL",
                    ),
                ),
                (
                    "private_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct storage URL (use for internal operations only).",
                        max_length=2000,
                        verbose_name="Private URL",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the generated thumbnail variant.",
                        max_length=2000,
                        verbose_name="Thumbnail URL",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organização"),
                            ("club", "Clube"),
                            ("competition", "Competição"),
                            ("match", "Jogo"),
                            ("news", "Notícia"),
                            ("player", "Jogador"),
                            ("system", "Sistema"),
                        ],
                        default="organization",
                        max_length=20,
                        verbose_name="Owner Type",
                    ),
                ),
                (
                    "owner_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the owning entity (Tenant, Club, etc.).",
                        null=True,
                        verbose_name="Owner ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("internal", "Interno"),
                            ("private", "Privado"),
                            ("signed", "Assinado (URL temporário)"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "A fazer upload"),
                            ("processing", "A processar"),
                            ("ready", "Pronto"),
                            ("archived", "Arquivado"),
                            ("deleted", "Eliminado"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant that owns this asset. Null for system assets.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Asset",
                "verbose_name_plural": "Media Assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organização"),
                            ("club", "Clube"),
                            ("competition", "Competição"),
                            ("match", "Jogo"),
                            ("news", "Notícia"),
                            ("player", "Jogador"),
                            ("system", "Sistema"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Owner Type",
                    ),
                ),
                (
                    "owner_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the owning entity (Tenant, Club, etc.).",
                        verbose_name="Owner ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("logo", "Logótipo"),
                            ("banner", "Banner"),
                            ("cover", "Capa"),
                            ("gallery", "Galeria"),
                            ("video", "Vídeo"),
                            ("document", "Documento"),
                            ("certificate", "Certificado"),
                            ("report", "Relatório"),
                            ("export", "Exportação"),
                            ("news_image", "Imagem de Notícia"),
                            ("sponsor_logo", "Logótipo de Patrocinador"),
                        ],
                        help_text="How is this asset used by the owner? (logo, banner, cover, etc.)",
                        max_length=30,
                        verbose_name="Role",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Sort order for gallery-type usages.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="media_assets.mediaasset",
                        verbose_name="Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Usage",
                "verbose_name_plural": "Media Usages",
                "ordering": ["owner_type", "owner_id", "role", "order"],
            },
        ),
        migrations.CreateModel(
            name="MediaVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "variant_type",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("thumbnail", "Thumbnail"),
                            ("small", "Pequeno"),
                            ("medium", "Médio"),
                            ("large", "Grande"),
                            ("webp", "WebP"),
                            ("avif", "AVIF"),
                        ],
                        max_length=20,
                        verbose_name="Variant Type",
                    ),
                ),
                (
                    "object_key",
                    models.CharField(
                        help_text="Storage path/key for this variant.",
                        max_length=1000,
                        verbose_name="Object Key",
                    ),
                ),
                (
                    "cdn_url",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="CDN URL"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Width (px)"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Height (px)"
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Size (bytes)"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME Type"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="media_assets.mediaasset",
                        verbose_name="Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Variant",
                "verbose_name_plural": "Media Variants",
                "ordering": ["variant_type"],
            },
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["tenant", "owner_type", "owner_id"],
                name="media_asset_tenant__73c335_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["asset_type", "category"], name="media_asset_asset_t_2757ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["status"], name="media_asset_status_9ea2f2_idx"),
        ),
        migrations.AddIndex(
            model_name="mediausage",
            index=models.Index(
                fields=["owner_type", "owner_id", "role", "is_active"],
                name="media_asset_owner_t_3d7751_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediavariant",
            index=models.Index(
                fields=["asset", "variant_type"], name="media_asset_asset_i_8d9815_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mediavariant",
            constraint=models.UniqueConstraint(
                fields=("asset", "variant_type"), name="unique_variant_per_asset"
            ),
        ),
    ]
