# Generated by Django 6.0 on 2026-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("organization", "Organização"),
                    ("club", "Clube"),
                    ("competition", "Competição"),
                    ("competition_regulation", "Regulamento de Competição"),
                    ("match", "Jogo"),
                    ("news", "Notícia"),
                    ("player", "Jogador"),
                    ("system", "Sistema"),
                ],
                default="organization",
                max_length=30,
                verbose_name="Owner Type",
            ),
        ),
        migrations.AlterField(
            model_name="mediausage",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("organization", "Organização"),
                    ("club", "Clube"),
                    ("competition", "Competição"),
                    ("competition_regulation", "Regulamento de Competição"),
                    ("match", "Jogo"),
                    ("news", "Notícia"),
                    ("player", "Jogador"),
                    ("system", "Sistema"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Owner Type",
            ),
        ),
    ]
