# Generated by Django 6.0 on 2026-07-02 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0003_alter_club_logo"),
        ("competitions", "0003_match_event"),
        ("core", "0004_alter_tenant_banner_alter_tenant_logo_and_more"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("joined_date", models.DateField(verbose_name="Joined Date")),
                (
                    "shirt_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Shirt Number"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Transfer Fee",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Request Date"
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed Date"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Rejection Reason"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="competitions.competition",
                        verbose_name="Competition",
                    ),
                ),
                (
                    "from_club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_out",
                        to="clubs.club",
                        verbose_name="From Club",
                    ),
                ),
                (
                    "from_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_out",
                        to="core.tenant",
                        verbose_name="From Tenant",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "to_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="clubs.club",
                        verbose_name="To Club",
                    ),
                ),
                (
                    "to_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="core.tenant",
                        verbose_name="To Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer",
                "verbose_name_plural": "Transfers",
                "ordering": ["-request_date"],
                "indexes": [
                    models.Index(
                        fields=["player"], name="transfers_t_player__85b9c2_idx"
                    ),
                    models.Index(
                        fields=["status"], name="transfers_t_status_91e571_idx"
                    ),
                    models.Index(
                        fields=["from_club"], name="transfers_t_from_cl_0ffdf1_idx"
                    ),
                    models.Index(
                        fields=["to_club"], name="transfers_t_to_club_05ffab_idx"
                    ),
                ],
            },
        ),
    ]
