# Generated by Django 6.0 on 2025-12-23 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0002_clubhistory'),
        ('core', '0001_initial'),
        ('jogadores', '0004_alter_player_position'),
        ('partidas', '0004_remove_match_stadium'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('goal', 'Golo'), ('yellow_card', 'Cartão Amarelo'), ('red_card', 'Cartão Vermelho'), ('substitution', 'Substituição'), ('whistle_start', 'Início de jogo'), ('whistle_end', 'Fim de jogo')], max_length=32)),
                ('minute', models.IntegerField(default=0)),
                ('is_own_goal', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='partidas.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='jogadores.player')),
                ('secondary_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_match_events', to='jogadores.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='clubes.club')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='core.tenant')),
            ],
            options={
                'ordering': ['minute', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_possession', models.IntegerField(default=50)),
                ('away_possession', models.IntegerField(default=50)),
                ('home_shots', models.IntegerField(default=0)),
                ('away_shots', models.IntegerField(default=0)),
                ('home_corners', models.IntegerField(default=0)),
                ('away_corners', models.IntegerField(default=0)),
                ('home_fouls', models.IntegerField(default=0)),
                ('away_fouls', models.IntegerField(default=0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='partidas.match')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchLineupEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('is_starter', models.BooleanField(default=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='partidas.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='jogadores.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='clubes.club')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_lineups', to='core.tenant')),
            ],
            options={
                'unique_together': {('match', 'team', 'player')},
            },
        ),
    ]
