# Generated by Django 6.0 on 2026-06-29 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_tenant_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, verbose_name="Slug"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Abbreviated name for tables and fixtures (e.g. 'PLU', '1º AGO').",
                        max_length=50,
                        null=True,
                        verbose_name="Short Name",
                    ),
                ),
                (
                    "logo",
                    models.URLField(
                        blank=True,
                        help_text="Cloudflare R2 URL for the club logo.",
                        max_length=500,
                        null=True,
                        verbose_name="Logo URL",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#014D40", max_length=7, verbose_name="Primary Color"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#94D3C1", max_length=7, verbose_name="Secondary Color"
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Founded Year"
                    ),
                ),
                (
                    "stadium_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stadium Name",
                    ),
                ),
                (
                    "stadium_capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Stadium Capacity"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Angola", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="City"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Is Public"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("suspended", "Suspenso"),
                            ("inactive", "Inativo"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClubMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Used when the member has no platform account.",
                        max_length=255,
                        null=True,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("player", "Jogador"),
                            ("coach", "Treinador"),
                            ("assistant_coach", "Treinador Adjunto"),
                            ("manager", "Gestor"),
                            ("physio", "Fisioterapeuta"),
                            ("staff", "Staff"),
                            ("president", "Presidente"),
                        ],
                        default="player",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "jersey_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Jersey Number"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GK", "Guarda-Redes"),
                            ("DF", "Defesa"),
                            ("MF", "Médio"),
                            ("FW", "Avançado"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Position",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "joined_at",
                    models.DateField(blank=True, null=True, verbose_name="Joined At"),
                ),
                (
                    "left_at",
                    models.DateField(blank=True, null=True, verbose_name="Left At"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Member",
                "verbose_name_plural": "Club Members",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="club",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_club_name_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="club",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="unique_club_slug_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("club", "user"),
                name="unique_club_member_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_active", True), ("jersey_number__isnull", False)
                ),
                fields=("club", "jersey_number"),
                name="unique_jersey_number_per_club",
            ),
        ),
    ]
