# Generated by Django 6.0 on 2025-12-20 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(max_length=20)),
                ('tournament_name', models.CharField(max_length=255)),
                ('placement', models.CharField(max_length=50)),
                ('is_trophy', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clubs.club')),
            ],
            options={
                'ordering': ['-season'],
            },
        ),
    ]
