# Generated by Django 6.0 on 2026-06-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_note_slug_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Club logo file (stored in configured DEFAULT_FILE_STORAGE).",
                max_length=500,
                null=True,
                upload_to="club-logos/",
                verbose_name="Logo",
            ),
        ),
    ]
