# Generated by Django 6.0 on 2026-07-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, editable=False, help_text='Deprecated legacy field. Use MediaAsset/MediaUsage (role=logo) instead.', max_length=500, null=True, upload_to='club-logos/', verbose_name='Logo (deprecated)'),
        ),
    ]
