# Generated by Django 6.0 on 2025-12-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_club_stadium_capacity_alter_club_stadium_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stadium_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
