# Generated by Django 6.0 on 2026-07-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_alter_club_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="logo",
        ),
    ]
