# Generated by Django 6.0 on 2026-07-05 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_remove_club_logo"),
        ("core", "0006_remove_tenant_banner_remove_tenant_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubAffiliationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Club Name")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Short Name"
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Founded Year"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="City"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Angola", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#014D40", max_length=7, verbose_name="Primary Color"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#94D3C1", max_length=7, verbose_name="Secondary Color"
                    ),
                ),
                (
                    "stadium_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stadium Name",
                    ),
                ),
                (
                    "stadium_capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Stadium Capacity"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Review Notes"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "club",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliation_request",
                        to="clubs.club",
                        verbose_name="Created Club",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_affiliation_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_affiliation_requests_submitted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_affiliation_requests",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club Affiliation Request",
                "verbose_name_plural": "Club Affiliation Requests",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "name"),
                        name="unique_club_affiliation_request_per_tenant_name",
                    )
                ],
            },
        ),
    ]
