# Generated by Django 6.0 on 2026-06-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("clubs", "0006_club_short_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="associated_clubs",
                to="accounts.organizacaoprofile",
            ),
        ),
    ]
