# Generated by Django 6.0 on 2026-07-05 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_clubdocument_clubsponsor"),
        ("core", "0006_remove_tenant_banner_remove_tenant_logo"),
        ("players", "0002_playerachievement_playerdocument_playervideo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent Transfer"),
                            ("loan", "Loan"),
                            ("free_agent", "Free Agent Signing"),
                        ],
                        default="permanent",
                        help_text="Permanent, loan, or free agent signing.",
                        max_length=20,
                        verbose_name="Transfer Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Loan Returned"),
                        ],
                        default="pending",
                        help_text="Workflow status: pending → approved → completed.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "transfer_date",
                    models.DateField(
                        help_text="Date transfer becomes effective.",
                        verbose_name="Transfer Date",
                    ),
                ),
                (
                    "announced_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Announced At"
                    ),
                ),
                (
                    "loan_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when loan ends and player returns to origin club.",
                        null=True,
                        verbose_name="Loan End Date",
                    ),
                ),
                (
                    "loan_return_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Whether player automatically returns on loan end date.",
                        verbose_name="Loan Return Mandatory",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Transfer fee in base currency (null for free agents/loans).",
                        max_digits=15,
                        null=True,
                        verbose_name="Transfer Fee",
                    ),
                ),
                (
                    "salary_contribution",
                    models.BooleanField(
                        default=False,
                        help_text="Whether origin club contributes to salary during loan.",
                        verbose_name="From Club Contributes Salary",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejected At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Rejection Reason"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Cancellation Reason"
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date loan was completed and player returned.",
                        null=True,
                        verbose_name="Returned At",
                    ),
                ),
                (
                    "made_permanent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether loan was converted to permanent transfer.",
                        verbose_name="Made Permanent",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_completed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completed By",
                    ),
                ),
                (
                    "from_club",
                    models.ForeignKey(
                        blank=True,
                        help_text="Club player is leaving (null for free agent signings).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_transfers",
                        to="clubs.club",
                        verbose_name="From Club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_transfers",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_rejected",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rejected By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "to_club",
                    models.ForeignKey(
                        help_text="Club player is joining.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transfers",
                        to="clubs.club",
                        verbose_name="To Club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer",
                "verbose_name_plural": "Transfers",
                "ordering": ["-transfer_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-transfer_date"],
                        name="clubs_trans_tenant__88874c_idx",
                    ),
                    models.Index(
                        fields=["player", "status"],
                        name="clubs_trans_player__636713_idx",
                    ),
                    models.Index(
                        fields=["from_club", "status"],
                        name="clubs_trans_from_cl_cdcc0e_idx",
                    ),
                    models.Index(
                        fields=["to_club", "status"],
                        name="clubs_trans_to_club_13b377_idx",
                    ),
                    models.Index(
                        fields=["transfer_type", "status"],
                        name="clubs_trans_transfe_a885cc_idx",
                    ),
                ],
            },
        ),
    ]
