# Generated by Django 6.0 on 2026-08-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_repair_approved_affiliation_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubaffiliationrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
