# Generated by Django 5.1.7 on 2026-09-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0011_repair_club_owner_tenant_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Masculino"),
                    ("female", "Feminino"),
                    ("mixed", "Misto"),
                ],
                default="mixed",
                help_text="Indica se o clube tem secções masculinas, femininas ou mistas.",
                max_length=10,
                verbose_name="Género do Clube",
            ),
        ),
    ]
