# Generated by Django 6.0 on 2026-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0012_club_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="acronym",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sigla de 2 a 5 letras para placares curtos e tickers (ex. 'APL').",
                max_length=10,
                verbose_name="Acronym",
            ),
        ),
        migrations.AddField(
            model_name="clubaffiliationrequest",
            name="acronym",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Acronym"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(
                help_text="Nome oficial completo do clube para documentos oficiais (ex. 'Atlético Clube Petróleos de Luanda').",
                max_length=255,
                verbose_name="Official Name",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nome usual/comum para placares e tabelas (ex. 'Petro de Luanda').",
                max_length=80,
                verbose_name="Short Name",
            ),
        ),
        migrations.AlterField(
            model_name="clubaffiliationrequest",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Club Official Name"),
        ),
        migrations.AlterField(
            model_name="clubaffiliationrequest",
            name="short_name",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Short Name"
            ),
        ),
    ]
