# Generated by Django 6.0 on 2026-06-21 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubeOrganizacaoRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovado"),
                            ("REJECTED", "Rejeitado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("mensagem", models.TextField(blank=True)),
                ("data_pedido", models.DateTimeField(auto_now_add=True)),
                ("data_decisao", models.DateTimeField(blank=True, null=True)),
                (
                    "clube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizacao_requests",
                        to="accounts.clubeprofile",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clube_requests",
                        to="accounts.organizacaoprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Afiliação Clube-Organização",
                "verbose_name_plural": "Pedidos de Afiliação Clube-Organização",
                "ordering": ["-data_pedido"],
            },
        ),
        migrations.CreateModel(
            name="JogadorClubeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovado"),
                            ("REJECTED", "Rejeitado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("mensagem", models.TextField(blank=True)),
                ("data_pedido", models.DateTimeField(auto_now_add=True)),
                ("data_decisao", models.DateTimeField(blank=True, null=True)),
                (
                    "clube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogador_requests",
                        to="accounts.clubeprofile",
                    ),
                ),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clube_requests",
                        to="accounts.jogadorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Ingresso Jogador-Clube",
                "verbose_name_plural": "Pedidos de Ingresso Jogador-Clube",
                "ordering": ["-data_pedido"],
            },
        ),
        migrations.CreateModel(
            name="JogadorHistoricoClube",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("numero_camisola", models.IntegerField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "clube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogador_history",
                        to="accounts.clubeprofile",
                    ),
                ),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clube_history",
                        to="accounts.jogadorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Clube de Jogador",
                "verbose_name_plural": "Históricos de Clubs de Jogadores",
                "ordering": ["-data_inicio"],
            },
        ),
    ]
