# Generated by Django 4.2.26 on 2026-06-30 14:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tenant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('competition_type', models.CharField(choices=[('league', 'Liga'), ('tournament', 'Torneio'), ('cup', 'Taça')], default='league', max_length=20, verbose_name='Type')),
                ('season', models.CharField(help_text='e.g. 2025/26', max_length=20, verbose_name='Season')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('completed', 'Concluída')], default='draft', max_length=20, verbose_name='Status')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='core.tenant', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug', 'season'), name='unique_competition_per_tenant_season'),
        ),
    ]
