# Generated by Django 6.0 on 2026-07-01 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_alter_club_logo"),
        ("competitions", "0001_initial"),
        ("core", "0004_alter_tenant_banner_alter_tenant_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("match_date", models.DateTimeField(verbose_name="Match Date/Time")),
                (
                    "round_number",
                    models.IntegerField(default=1, verbose_name="Round Number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendado"),
                            ("live", "Em Curso"),
                            ("finished", "Concluído"),
                            ("postponed", "Adiado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "home_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Home Score"
                    ),
                ),
                (
                    "away_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Away Score"
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Venue/Stadium",
                    ),
                ),
                (
                    "away_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="clubs.club",
                        verbose_name="Away Club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="competitions.competition",
                        verbose_name="Competition",
                    ),
                ),
                (
                    "home_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="clubs.club",
                        verbose_name="Home Club",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["round_number", "match_date"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registered At"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_registrations",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="competitions.competition",
                        verbose_name="Competition",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_registrations",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Registration",
                "verbose_name_plural": "Competition Registrations",
                "ordering": ["-registered_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competition", "club"),
                        name="unique_club_per_competition",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "played",
                    models.IntegerField(default=0, verbose_name="Matches Played"),
                ),
                ("won", models.IntegerField(default=0, verbose_name="Matches Won")),
                ("drawn", models.IntegerField(default=0, verbose_name="Matches Drawn")),
                ("lost", models.IntegerField(default=0, verbose_name="Matches Lost")),
                ("goals_for", models.IntegerField(default=0, verbose_name="Goals For")),
                (
                    "goals_against",
                    models.IntegerField(default=0, verbose_name="Goals Against"),
                ),
                (
                    "goal_difference",
                    models.IntegerField(default=0, verbose_name="Goal Difference"),
                ),
                ("points", models.IntegerField(default=0, verbose_name="Points")),
                ("position", models.IntegerField(default=1, verbose_name="Position")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="competitions.competition",
                        verbose_name="Competition",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standing",
                "verbose_name_plural": "Standings",
                "ordering": ["position", "-points", "-goal_difference", "-goals_for"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competition", "club"),
                        name="unique_club_standing_per_competition",
                    )
                ],
            },
        ),
    ]
