# Generated by Django 6.0 on 2026-07-01 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_alter_club_logo"),
        ("competitions", "0002_match_competitionregistration_standing"),
        ("core", "0004_alter_tenant_banner_alter_tenant_logo_and_more"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("goal", "Golo"),
                            ("own_goal", "Golo Contra"),
                            ("yellow_card", "Cartão Amarelo"),
                            ("red_card", "Cartão Vermelho"),
                            ("yellow_red", "Segundo Amarelo / Vermelho"),
                            ("substitution_in", "Substituição (Entra)"),
                            ("substitution_out", "Substituição (Sai)"),
                            ("penalty_scored", "Penálti Marcado"),
                            ("penalty_missed", "Penálti Falhado"),
                        ],
                        max_length=30,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "minute",
                    models.PositiveSmallIntegerField(
                        help_text="Match minute when the event occurred (1-120, or 0 for pre-match).",
                        verbose_name="Minute",
                    ),
                ),
                (
                    "extra_time",
                    models.BooleanField(
                        default=False,
                        help_text="True if the minute is in extra time / stoppage time.",
                        verbose_name="Extra Time",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Notes"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        help_text="Club the event is attributed to (attacker's club for goals, fouling club for cards).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="competitions.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_events",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "player_off",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only used for SUBSTITUTION_IN — the player being replaced.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substituted_out_events",
                        to="players.player",
                        verbose_name="Player (Off)",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Event",
                "verbose_name_plural": "Match Events",
                "ordering": ["match", "minute"],
                "indexes": [
                    models.Index(
                        fields=["match", "minute"],
                        name="competition_match_i_d5064c_idx",
                    ),
                    models.Index(
                        fields=["player"], name="competition_player__393503_idx"
                    ),
                ],
            },
        ),
    ]
