# Generated by Django 6.0 on 2026-07-05 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_clubdocument_clubsponsor"),
        ("competitions", "0004_competitionregulation"),
        ("core", "0006_remove_tenant_banner_remove_tenant_logo"),
        ("players", "0002_playerachievement_playerdocument_playervideo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionRanking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "ranking_type",
                    models.CharField(
                        choices=[
                            ("top_scorer", "Melhor Marcador"),
                            ("top_assists", "Mais Assistências"),
                            ("fair_play_player", "Fair Play (Jogador)"),
                            ("fair_play_club", "Fair Play (Clube)"),
                            ("historical_points", "Pontos Históricos"),
                            ("historical_titles", "Títulos Históricos"),
                            ("most_appearances", "Mais Partidas"),
                            ("most_clean_sheets", "Mais Clean Sheets"),
                            ("player_of_the_year", "Jogador do Ano"),
                            ("young_player", "Jogador Jovem"),
                        ],
                        max_length=30,
                        verbose_name="Ranking Type",
                    ),
                ),
                (
                    "aggregation_level",
                    models.CharField(
                        choices=[
                            ("competition", "Por Competição"),
                            ("season", "Por Temporada"),
                            ("all_time", "Histórico"),
                            ("monthly", "Mensal"),
                        ],
                        default="season",
                        max_length=20,
                        verbose_name="Aggregation Level",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g., '2024/2025', '2025'.",
                        max_length=20,
                        verbose_name="Season",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="For monthly rankings (1-12).",
                        null=True,
                        verbose_name="Month",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year for annual or monthly rankings.",
                        null=True,
                        verbose_name="Year",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Current position in the ranking.",
                        verbose_name="Position",
                    ),
                ),
                (
                    "previous_position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Position in the last update.",
                        null=True,
                        verbose_name="Previous Position",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="The ranking value (goals, points, fair play score, etc.).",
                        max_digits=10,
                        verbose_name="Value",
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed stats for this ranking entry.",
                        verbose_name="Statistics",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an officially verified ranking.",
                        verbose_name="Is Official",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific competition (null for cross-competition rankings).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="competitions.competition",
                        verbose_name="Competition",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Ranking",
                "verbose_name_plural": "Competition Rankings",
                "ordering": ["ranking_type", "season", "position"],
                "indexes": [
                    models.Index(
                        fields=["ranking_type", "season", "position"],
                        name="competition_ranking_fd4b62_idx",
                    ),
                    models.Index(
                        fields=["player", "ranking_type"],
                        name="competition_player__ae2946_idx",
                    ),
                    models.Index(
                        fields=["club", "ranking_type"],
                        name="competition_club_id_b74f91_idx",
                    ),
                    models.Index(
                        fields=["tenant", "ranking_type", "season"],
                        name="competition_tenant__034c0b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("player__isnull", False)),
                        fields=(
                            "tenant",
                            "ranking_type",
                            "aggregation_level",
                            "season",
                            "player",
                        ),
                        name="unique_player_ranking_per_season",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("club__isnull", False)),
                        fields=(
                            "tenant",
                            "ranking_type",
                            "aggregation_level",
                            "season",
                            "club",
                        ),
                        name="unique_club_ranking_per_season",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerSuspension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "suspension_type",
                    models.CharField(
                        choices=[
                            ("yellow_accumulation", "Acumulação de Cartões Amarelos"),
                            ("red_card", "Cartão Vermelho Direto"),
                            ("yellow_red", "Segundo Amarelo / Vermelho"),
                            ("disciplinary", "Ação Disciplinar"),
                            ("manual", "Suspensão Manual"),
                        ],
                        max_length=30,
                        verbose_name="Suspension Type",
                    ),
                ),
                (
                    "matches_suspended",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Number of matches the player must miss.",
                        verbose_name="Matches Suspended",
                    ),
                ),
                (
                    "matches_served",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of matches already served.",
                        verbose_name="Matches Served",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("active", "Ativa"),
                            ("served", "Cumprida"),
                            ("cancelled", "Cancelada"),
                            ("appealed", "Em Recurso"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Date from which the suspension is effective.",
                        verbose_name="Effective From",
                    ),
                ),
                (
                    "effective_until",
                    models.DateField(
                        blank=True,
                        help_text="Date until which the suspension is effective (if fixed period).",
                        null=True,
                        verbose_name="Effective Until",
                    ),
                ),
                (
                    "served_on",
                    models.DateField(
                        blank=True,
                        help_text="Date when the suspension was fully served.",
                        null=True,
                        verbose_name="Served On",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Detailed reason for the suspension.",
                        max_length=500,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Internal Notes"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Cancellation Reason",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions_cancelled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelled By",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        help_text="The club the player was registered with when suspended.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_suspensions",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_suspensions",
                        to="competitions.competition",
                        verbose_name="Competition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_suspensions",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "trigger_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific match event that triggered this suspension.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspension_generated",
                        to="competitions.matchevent",
                        verbose_name="Trigger Event",
                    ),
                ),
                (
                    "trigger_match",
                    models.ForeignKey(
                        blank=True,
                        help_text="The match where the card/event occurred (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions_triggered",
                        to="competitions.match",
                        verbose_name="Trigger Match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Suspension",
                "verbose_name_plural": "Player Suspensions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["player", "competition", "status"],
                        name="competition_player__6509c6_idx",
                    ),
                    models.Index(
                        fields=["competition", "status"],
                        name="competition_competi_3b9bee_idx",
                    ),
                    models.Index(
                        fields=["club", "status"], name="competition_club_id_2912c9_idx"
                    ),
                ],
            },
        ),
    ]
