# Generated by Django 6.0 on 2026-07-05 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_clubdocument_clubsponsor"),
        ("competitions", "0005_add_player_suspension_and_ranking"),
        ("core", "0006_remove_tenant_banner_remove_tenant_logo"),
        ("media_assets", "0002_alter_mediaasset_owner_type_and_more"),
        ("players", "0002_playerachievement_playerdocument_playervideo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LineupSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("submitted", "Submetida"),
                            ("confirmed", "Confirmada"),
                            ("locked", "Bloqueada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "formation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Formation used (e.g., '4-3-3', '4-4-2').",
                        max_length=10,
                        verbose_name="Formation",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed At"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_submissions",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lineup_submissions_confirmed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmed By",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_submissions",
                        to="competitions.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lineup_submissions_done",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_submissions",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lineup Submission",
                "verbose_name_plural": "Lineup Submissions",
                "ordering": ["match", "club"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "club"),
                        name="unique_lineup_submission_per_match_club",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchLineup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("starter", "Titular"),
                            ("substitute", "Suplente"),
                            ("unused", "Não Utilizado"),
                        ],
                        default="substitute",
                        help_text="Starter, substitute, or unused.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("gk", "Guarda-Redes"),
                            ("cb", "Defesa Central"),
                            ("lb", "Defesa Esquerdo"),
                            ("rb", "Defesa Direito"),
                            ("lwb", "Lateral Esquerdo"),
                            ("rwb", "Lateral Direito"),
                            ("cm", "Médio Centro"),
                            ("cdm", "Médio Defensivo"),
                            ("cam", "Médio Ofensivo"),
                            ("lm", "Médio Esquerdo"),
                            ("rm", "Médio Direito"),
                            ("lw", "Extremo Esquerdo"),
                            ("rw", "Extremo Direito"),
                            ("st", "Avançado"),
                            ("cf", "Ponta de Lança"),
                        ],
                        help_text="Position played in this match.",
                        max_length=20,
                        verbose_name="Position",
                    ),
                ),
                (
                    "shirt_number",
                    models.PositiveSmallIntegerField(
                        help_text="Shirt number worn in this match.",
                        verbose_name="Shirt Number",
                    ),
                ),
                (
                    "is_captain",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this player is the team captain.",
                        verbose_name="Is Captain",
                    ),
                ),
                (
                    "is_goalkeeper",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this player is the goalkeeper.",
                        verbose_name="Is Goalkeeper",
                    ),
                ),
                (
                    "formation_position",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Position in formation (1-11 for starters).",
                        null=True,
                        verbose_name="Formation Position",
                    ),
                ),
                (
                    "minutes_played",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Minutes played (populated after match).",
                        null=True,
                        verbose_name="Minutes Played",
                    ),
                ),
                (
                    "substituted_in_minute",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Minute when player came on (for substitutes).",
                        null=True,
                        verbose_name="Substituted In Minute",
                    ),
                ),
                (
                    "substituted_out_minute",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Minute when player went off.",
                        null=True,
                        verbose_name="Substituted Out Minute",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_lineups",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="competitions.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_lineups",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lineups_submitted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_lineups",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Lineup",
                "verbose_name_plural": "Match Lineups",
                "ordering": ["match", "club", "-status", "formation_position"],
                "indexes": [
                    models.Index(
                        fields=["match", "club"], name="competition_match_i_4f3662_idx"
                    ),
                    models.Index(
                        fields=["match", "club", "status"],
                        name="competition_match_i_a07990_idx",
                    ),
                    models.Index(
                        fields=["player", "match"],
                        name="competition_player__e86810_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "club", "player"),
                        name="unique_player_in_match_lineup",
                    ),
                    models.UniqueConstraint(
                        fields=("match", "club", "shirt_number"),
                        name="unique_shirt_number_in_match_lineup",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("full", "Relatório Completo"),
                            ("summary", "Resumo"),
                            ("statistics", "Estatísticas"),
                            ("events", "Eventos"),
                            ("official", "Relatório Oficial (Súmula)"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("generating", "A Gerar"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured report data (JSON).",
                        verbose_name="Report Data",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct URL to PDF (if generated).",
                        max_length=2000,
                        verbose_name="PDF URL",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Generated At"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Celery task ID for async generation.",
                        max_length=255,
                        verbose_name="Task ID",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="Error Message"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Requested At"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_reports_generated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generated By",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="competitions.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "pdf_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="PDF file stored in DAM.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_reports",
                        to="media_assets.mediaasset",
                        verbose_name="PDF Asset",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_reports_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_reports",
                        to="core.tenant",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Report",
                "verbose_name_plural": "Match Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["match", "report_type"],
                        name="competition_match_i_dabfef_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="competition_tenant__132a9c_idx",
                    ),
                ],
            },
        ),
    ]
