# Generated by Django 6.0 on 2026-07-05 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_clubdocument_clubsponsor"),
        ("competitions", "0006_add_match_lineup_and_report"),
        ("media_assets", "0002_alter_mediaasset_owner_type_and_more"),
        ("players", "0002_playerachievement_playerdocument_playervideo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "minute",
                    models.PositiveSmallIntegerField(
                        help_text="Minute when goal was scored (1-180).",
                        verbose_name="Minute",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("penalty", "Penalty"),
                            ("own_goal", "Own Goal"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Goal Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "ordering": ["match", "minute"],
            },
        ),
        migrations.CreateModel(
            name="MatchStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "possession",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Percentage of ball possession (0-100).",
                        null=True,
                        verbose_name="Ball Possession %",
                    ),
                ),
                (
                    "shots_on_goal",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Shots on Goal"
                    ),
                ),
                (
                    "shots_off_goal",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Shots off Goal"
                    ),
                ),
                (
                    "passes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Total Passes"
                    ),
                ),
                (
                    "passes_accuracy",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Percentage of accurate passes (0-100).",
                        null=True,
                        verbose_name="Pass Accuracy %",
                    ),
                ),
                (
                    "fouls",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Fouls Committed"
                    ),
                ),
                (
                    "yellow_cards",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Yellow Cards"
                    ),
                ),
                (
                    "red_cards",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Red Cards"
                    ),
                ),
                (
                    "corner_kicks",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Corner Kicks"
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Statistic",
                "verbose_name_plural": "Match Statistics",
                "ordering": ["match", "club"],
            },
        ),
        migrations.RemoveIndex(
            model_name="matchreport",
            name="competition_tenant__132a9c_idx",
        ),
        migrations.AddField(
            model_name="matchreport",
            name="away_goals_against",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Away Goals Against"
            ),
        ),
        migrations.AddField(
            model_name="matchreport",
            name="away_score",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Away Score"
            ),
        ),
        migrations.AddField(
            model_name="matchreport",
            name="finalized_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Finalized At"
            ),
        ),
        migrations.AddField(
            model_name="matchreport",
            name="finalized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match_reports_finalized",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Finalized By",
            ),
        ),
        migrations.AddField(
            model_name="matchreport",
            name="home_goals_against",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Home Goals Against"
            ),
        ),
        migrations.AddField(
            model_name="matchreport",
            name="home_score",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Home Score"
            ),
        ),
        migrations.AddField(
            model_name="matchreport",
            name="match_duration",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Match Duration (minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="matchreport",
            name="match",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_report",
                to="competitions.match",
                verbose_name="Match",
            ),
        ),
        migrations.AlterField(
            model_name="matchreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("generating", "A Gerar"),
                    ("completed", "Concluído"),
                    ("finalized", "Finalizado"),
                    ("failed", "Falhou"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="matchreport",
            index=models.Index(fields=["status"], name="competition_status_e56779_idx"),
        ),
        migrations.AddField(
            model_name="goal",
            name="assist_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assists",
                to="players.player",
                verbose_name="Assist Player",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="clubs.club",
                verbose_name="Club",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="competitions.match",
                verbose_name="Match",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="players.player",
                verbose_name="Player",
            ),
        ),
        migrations.AddField(
            model_name="matchstats",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_stats",
                to="clubs.club",
                verbose_name="Club",
            ),
        ),
        migrations.AddField(
            model_name="matchstats",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matchstats_set",
                to="competitions.match",
                verbose_name="Match",
            ),
        ),
        migrations.RemoveField(
            model_name="matchreport",
            name="tenant",
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["match", "minute"], name="competition_match_i_faed35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["player", "match"], name="competition_player__9b50c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchstats",
            index=models.Index(
                fields=["match", "club"], name="competition_match_i_f0a3ef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchstats",
            constraint=models.UniqueConstraint(
                fields=("match", "club"), name="unique_match_club_stats"
            ),
        ),
    ]
