# Generated by Django 6.0 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0007_add_goal_and_match_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="config",
            field=models.JSONField(blank=True, default=dict, verbose_name="Configuration"),
        ),
    ]
