# Generated by Django 6.0 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0008_add_config_to_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="group_id",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Group ID"),
        ),
        migrations.AddField(
            model_name="match",
            name="phase",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Phase"),
        ),
        migrations.AddField(
            model_name="match",
            name="round_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Round Name"),
        ),
        migrations.AddField(
            model_name="standing",
            name="group_id",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Group ID"),
        ),
        migrations.AddField(
            model_name="standing",
            name="phase",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Phase"),
        ),
        migrations.RemoveConstraint(
            model_name="standing",
            name="unique_club_standing_per_competition",
        ),
        migrations.AddConstraint(
            model_name="standing",
            constraint=models.UniqueConstraint(
                fields=("tenant", "competition", "club", "phase", "group_id"),
                name="unique_club_standing_per_competition_context",
            ),
        ),
        migrations.AddIndex(
            model_name="standing",
            index=models.Index(fields=["competition", "phase", "group_id"], name="standing_ctx_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["competition", "phase", "group_id"], name="match_ctx_idx"),
        ),
    ]
