# Generated by Django 6.0 on 2026-07-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_add_context_fields_to_match_and_standing'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='match_ctx_idx',
        ),
        migrations.RemoveIndex(
            model_name='standing',
            name='standing_ctx_idx',
        ),
    ]
