# Generated by Django 6.0 on 2026-07-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0011_remove_match_match_ctx_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchlineup",
            name="eligibility_warning",
            field=models.CharField(
                blank=True,
                help_text="Warning message if player has eligibility issues.",
                max_length=255,
                null=True,
                verbose_name="Eligibility Warning",
            ),
        ),
        migrations.AddField(
            model_name="matchlineup",
            name="eligible",
            field=models.BooleanField(
                default=True,
                help_text="Whether this player is eligible for this match.",
                verbose_name="Is Eligible",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Agendado"),
                    ("pre_match", "Pré-jogo"),
                    ("live", "Em Curso"),
                    ("halftime", "Intervalo"),
                    ("finished", "Concluído"),
                    ("postponed", "Adiado"),
                    ("cancelled", "Cancelado"),
                    ("walkover", "Walkover"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
