# Generated by Django 6.0 on 2026-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "competitions",
            "0012_matchlineup_eligibility_warning_matchlineup_eligible_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("goal", "Golo"),
                    ("own_goal", "Golo Contra"),
                    ("yellow_card", "Cartão Amarelo"),
                    ("red_card", "Cartão Vermelho"),
                    ("yellow_red", "Segundo Amarelo / Vermelho"),
                    ("substitution_in", "Substituição (Entra)"),
                    ("substitution_out", "Substituição (Sai)"),
                    ("penalty_scored", "Penálti Marcado"),
                    ("penalty_missed", "Penálti Falhado"),
                    ("injury", "Lesão"),
                    ("var_review", "Revisão VAR"),
                    ("kickoff", "Bola em jogo"),
                    ("halftime", "Intervalo"),
                    ("fulltime", "Fim de jogo"),
                ],
                max_length=30,
                verbose_name="Event Type",
            ),
        ),
    ]
