# Generated by Django 6.0 on 2026-08-02 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0009_repair_approved_affiliation_requests"),
        ("competitions", "0015_unique_slug_per_tenant"),
        ("core", "0006_remove_tenant_banner_remove_tenant_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TacticalPositions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("positions", models.JSONField(blank=True, default=list)),
                ("version", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                "verbose_name": "Tactical Positions",
                "verbose_name_plural": "Tactical Positions",
            },
        ),
        migrations.RemoveConstraint(
            model_name="competition",
            name="unique_competition_slug_per_tenant",
        ),
        migrations.AddField(
            model_name="tacticalpositions",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tactical_positions",
                to="clubs.club",
                verbose_name="Club",
            ),
        ),
        migrations.AddField(
            model_name="tacticalpositions",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tactical_positions",
                to="competitions.match",
                verbose_name="Match",
            ),
        ),
        migrations.AddField(
            model_name="tacticalpositions",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tactical_positions",
                to="core.tenant",
                verbose_name="Organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="tacticalpositions",
            constraint=models.UniqueConstraint(
                fields=("match", "club"), name="unique_tactical_per_match_club"
            ),
        ),
    ]
