# Generated by Django 6.0 on 2026-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0017_linesubmission_review_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineupsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("submitted", "Submetida"),
                    ("confirmed", "Confirmada"),
                    ("rejected", "Rejeitada"),
                    ("locked", "Bloqueada"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
