# Generated by Django 6.0 on 2026-08-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_alter_lineupsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_minute',
            field=models.PositiveSmallIntegerField(default=0, help_text='Live minute value for the current period.', verbose_name='Current Minute'),
        ),
        migrations.AddField(
            model_name='match',
            name='current_period',
            field=models.CharField(blank=True, choices=[('first_half', '1º Tempo'), ('second_half', '2º Tempo'), ('extra_time', 'Prorrogação'), ('penalties', 'Penaltis'), ('halftime', 'Intervalo'), ('fulltime', 'Fim de jogo')], default=None, max_length=20, null=True, verbose_name='Current Period'),
        ),
    ]
