# Generated by Django 6.0 on 2026-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0025_match_clock_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchclockaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="matchclockaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
