# Generated by Django 6.0 on 2026-09-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_alter_matchclockaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description, notes or regulations summary', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expected ending date of the competition', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_end_date',
            field=models.DateField(blank=True, help_text='Closing date for club registrations', null=True, verbose_name='Registration End Date'),
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_start_date',
            field=models.DateField(blank=True, help_text='Opening date for club registrations', null=True, verbose_name='Registration Start Date'),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(blank=True, help_text='Expected starting date of the competition', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('completed', 'Concluída'), ('inactive', 'Inativa')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
