# Generated by Django 5.1.7 on 2026-09-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0027_competition_description_competition_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="allowed_genders",
            field=models.CharField(
                choices=[
                    ("male", "Masculino"),
                    ("female", "Feminino"),
                    ("mixed", "Misto"),
                ],
                default="male",
                help_text="Género dos atletas/equipas autorizados a competir.",
                max_length=10,
                verbose_name="Géneros Permitidos",
            ),
        ),
    ]
