# Generated by Django 5.1.7 on 2026-09-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0028_competition_allowed_genders"),
        ("players", "0018_player_gender_playercategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Escalão etário da competição (ex: Sénior, Júnior, Sub-17).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competitions",
                to="players.playercategory",
                verbose_name="Categoria / Escalão",
            ),
        ),
    ]
