# Generated by Django 6.0 on 2025-12-21 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_slug', models.SlugField(unique=True)),
                ('organization_type', models.CharField(choices=[('league', 'Liga Profissional'), ('amateur', 'Torneio Amador'), ('school', 'Escola / Formação'), ('federation', 'Federação')], default='league', max_length=50)),
                ('country', models.CharField(default='Angola', max_length=100)),
                ('primary_color', models.CharField(default='#22c55e', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='onboarding/logos/')),
                ('season_name', models.CharField(default='Temporada 2024/25', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
