# Generated by Django 6.0 on 2025-12-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingrequest',
            name='season_name',
            field=models.CharField(default='2024/25', max_length=255),
        ),
    ]
