# Generated by Django 6.0 on 2026-01-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_onboardingrequest_season_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingrequest',
            name='organization_type',
            field=models.CharField(choices=[('league', 'Liga Profissional'), ('association', 'Associação'), ('tournament', 'Torneio'), ('amateur', 'Amador / Corporativo'), ('school', 'Escola / Formação'), ('federation', 'Federação')], default='league', max_length=50),
        ),
    ]
