# Generated by Django 6.0 on 2026-07-01 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0003_alter_club_logo"),
        ("competitions", "0001_initial"),
        ("core", "0004_alter_tenant_banner_alter_tenant_logo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Last Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nationality",
                    ),
                ),
                (
                    "height_cm",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Height (cm)"
                    ),
                ),
                (
                    "weight_kg",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Weight (kg)"
                    ),
                ),
                (
                    "foot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Preferred Foot",
                    ),
                ),
                (
                    "primary_position",
                    models.CharField(
                        choices=[
                            ("gk", "Goalkeeper"),
                            ("cb", "Center Back"),
                            ("lb", "Left Back"),
                            ("rb", "Right Back"),
                            ("lwb", "Left Wing Back"),
                            ("rwb", "Right Wing Back"),
                            ("cm", "Central Midfielder"),
                            ("cdm", "Defensive Midfielder"),
                            ("cam", "Attacking Midfielder"),
                            ("lm", "Left Midfielder"),
                            ("rm", "Right Midfielder"),
                            ("lw", "Left Winger"),
                            ("rw", "Right Winger"),
                            ("st", "Striker"),
                            ("cf", "Center Forward"),
                            ("multiple", "Multiple Positions"),
                        ],
                        default="multiple",
                        max_length=20,
                        verbose_name="Primary Position",
                    ),
                ),
                (
                    "shirt_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Preferred Shirt Number"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biography"),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Avatar URL"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("banned", "Banned"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_matches",
                    models.IntegerField(default=0, verbose_name="Total Matches Played"),
                ),
                (
                    "total_goals",
                    models.IntegerField(default=0, verbose_name="Total Goals"),
                ),
                (
                    "total_assists",
                    models.IntegerField(default=0, verbose_name="Total Assists"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Associated User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "shirt_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Shirt Number"
                    ),
                ),
                ("joined_date", models.DateField(verbose_name="Joined Date")),
                (
                    "left_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Left Date (if transferred)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("loaned", "On Loan"),
                            ("suspended", "Suspended"),
                            ("retired", "Retired"),
                            ("transferred", "Transferred"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "matches_played",
                    models.IntegerField(default=0, verbose_name="Matches Played"),
                ),
                ("goals", models.IntegerField(default=0, verbose_name="Goals")),
                ("assists", models.IntegerField(default=0, verbose_name="Assists")),
                (
                    "yellow_cards",
                    models.IntegerField(default=0, verbose_name="Yellow Cards"),
                ),
                ("red_cards", models.IntegerField(default=0, verbose_name="Red Cards")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_registrations",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_registrations",
                        to="competitions.competition",
                        verbose_name="Competition",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_registrations",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Registration",
                "verbose_name_plural": "Player Registrations",
                "ordering": ["-joined_date"],
            },
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["slug"], name="players_pla_slug_839a41_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["status"], name="players_pla_status_6a7a33_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["nationality"], name="players_pla_nationa_103a64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["primary_position"], name="players_pla_primary_43b5ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["user"], name="players_pla_user_id_975093_idx"),
        ),
        migrations.AddIndex(
            model_name="playerregistration",
            index=models.Index(
                fields=["club", "status"], name="players_pla_club_id_c87da0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerregistration",
            index=models.Index(
                fields=["player", "status"], name="players_pla_player__fa7d2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerregistration",
            index=models.Index(
                fields=["tenant", "club"], name="players_pla_tenant__570cfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerregistration",
            index=models.Index(
                fields=["joined_date"], name="players_pla_joined__f25b8a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["registered", "loaned"])),
                fields=("player", "club", "competition"),
                name="unique_active_player_club_competition",
            ),
        ),
    ]
