# Generated by Django 6.0 on 2026-07-05 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_clubdocument_clubsponsor"),
        ("competitions", "0004_competitionregulation"),
        ("media_assets", "0002_alter_mediaasset_owner_type_and_more"),
        ("players", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Achievement title (e.g., 'Campeão da Girabola 2025')",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("league_title", "Título de Liga"),
                            ("cup_title", "Título de Taça"),
                            ("super_cup", "Super Taça"),
                            ("tournament", "Torneio"),
                            (
                                "international_club",
                                "Competição Internacional de Clubes",
                            ),
                            ("top_scorer", "Melhor Marcador"),
                            ("best_player", "Melhor Jogador"),
                            ("mvp", "Jogador Mais Valioso"),
                            ("best_goalkeeper", "Melhor Guarda-Redes"),
                            ("best_young_player", "Melhor Jovem"),
                            ("golden_boot", "Chuteira de Ouro"),
                            ("golden_ball", "Bola de Ouro"),
                            ("milestone_100_goals", "100 Golos"),
                            ("milestone_500_appearances", "500 Jogos"),
                            ("milestone_100_caps", "100 Internacionalizações"),
                            ("national_team_cap", "Internacionalização"),
                            ("world_cup", "Copa do Mundo"),
                            ("continental_cup", "Copa Continental"),
                            ("olympics", "Jogos Olímpicos"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Achievement Type",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("club", "Nível de Clube"),
                            ("national", "Nível Nacional"),
                            ("continental", "Nível Continental"),
                            ("international", "Nível Internacional"),
                            ("world", "Nível Mundial"),
                        ],
                        default="club",
                        max_length=20,
                        verbose_name="Achievement Level",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the achievement",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "date_achieved",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Achieved"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="Season when achievement was won (e.g., '2024/2025')",
                        max_length=20,
                        null=True,
                        verbose_name="Season",
                    ),
                ),
                (
                    "trophy_image",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Trophy Image URL",
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Certificate URL",
                    ),
                ),
                (
                    "stats_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Player stats at the time of achievement (goals, assists, matches)",
                        null=True,
                        verbose_name="Stats Snapshot",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Verified achievements have been confirmed by officials",
                        verbose_name="Is Verified",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        help_text="Club the player was at when achieving this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_achievements",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Competition this achievement is related to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_achievements",
                        to="competitions.competition",
                        verbose_name="Competition",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Achievement",
                "verbose_name_plural": "Player Achievements",
                "ordering": ["-date_achieved", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["player", "achievement_type"],
                        name="players_pla_player__e48e7e_idx",
                    ),
                    models.Index(
                        fields=["player", "date_achieved"],
                        name="players_pla_player__6ea119_idx",
                    ),
                    models.Index(
                        fields=["player", "season"],
                        name="players_pla_player__bb0a82_idx",
                    ),
                    models.Index(
                        fields=["player", "is_verified"],
                        name="players_pla_player__921351_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title (e.g., 'Contrato com Petro de Luanda - 2025')",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("contract", "Contrato"),
                            ("passport", "Passaporte/Bilhete de Identidade"),
                            ("medical", "Certificado Médico"),
                            ("license", "Licença de Jogador"),
                            ("certificate", "Certificado"),
                            ("transfer", "Documento de Transferência"),
                            ("insurance", "Seguro"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about the document",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("verified", "Verificado"),
                            ("rejected", "Rejeitado"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="Valid From"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="Valid Until"),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=True,
                        help_text="Private documents are only visible to authorized users",
                        verbose_name="Is Private",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Uploaded document file via DAM",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_documents",
                        to="media_assets.mediaasset",
                        verbose_name="Media Asset",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        help_text="Club this document is associated with (e.g., for contracts)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_documents",
                        to="clubs.club",
                        verbose_name="Related Club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_documents_verified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Document",
                "verbose_name_plural": "Player Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["player", "category"],
                        name="players_pla_player__50d50f_idx",
                    ),
                    models.Index(
                        fields=["player", "status"],
                        name="players_pla_player__75116e_idx",
                    ),
                    models.Index(
                        fields=["valid_until"], name="players_pla_valid_u_50e7b0_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "title"),
                        name="unique_player_document_title_per_player",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Video title (e.g., 'Golo frente ao Petro - Girabola 2025')",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or context for the video",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("highlights", "Melhores Momentos"),
                            ("skills", "Demonstração de Skills"),
                            ("interview", "Entrevista"),
                            ("match_clip", "Clip de Jogo"),
                            ("training", "Treino"),
                            ("other", "Outro"),
                        ],
                        default="highlights",
                        max_length=20,
                        verbose_name="Video Type",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="External video URL (YouTube, Vimeo, etc.)",
                        max_length=500,
                        null=True,
                        verbose_name="Video URL",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Thumbnail URL",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duration (seconds)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("published", "Publicado"),
                            ("archived", "Arquivado"),
                        ],
                        default="published",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured videos appear prominently on the player profile",
                        verbose_name="Is Featured",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order on player profile",
                        verbose_name="Order",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        help_text="Match this video is from (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_videos",
                        to="competitions.match",
                        verbose_name="Related Match",
                    ),
                ),
                (
                    "media_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Uploaded video file via DAM",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_videos",
                        to="media_assets.mediaasset",
                        verbose_name="Media Asset",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Video",
                "verbose_name_plural": "Player Videos",
                "ordering": ["-is_featured", "order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["player", "status"],
                        name="players_pla_player__dd5cf7_idx",
                    ),
                    models.Index(
                        fields=["player", "video_type"],
                        name="players_pla_player__3bc9a2_idx",
                    ),
                    models.Index(
                        fields=["player", "is_featured"],
                        name="players_pla_player__79ea09_idx",
                    ),
                ],
            },
        ),
    ]
