# Generated by Django 6.0 on 2026-07-12 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_add_transfer_model"),
        ("competitions", "0007_add_goal_and_match_stats"),
        ("core", "0006_remove_tenant_banner_remove_tenant_logo"),
        ("players", "0002_playerachievement_playerdocument_playervideo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerRegistrationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("joined_date", models.DateField(verbose_name="Requested Join Date")),
                (
                    "shirt_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Shirt Number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Review Notes"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_registration_requests",
                        to="clubs.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_registration_requests",
                        to="competitions.competition",
                        verbose_name="Competition",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_requests",
                        to="players.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_request",
                        to="players.playerregistration",
                        verbose_name="Created Registration",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_registration_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_registration_requests_submitted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_registration_requests",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Registration Request",
                "verbose_name_plural": "Player Registration Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "status"], name="players_pla_club_id_8ad2ec_idx"
                    ),
                    models.Index(
                        fields=["player", "status"],
                        name="players_pla_player__e9ecaa_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="players_pla_tenant__f89f39_idx",
                    ),
                ],
            },
        ),
    ]
