# Generated by Django 6.0 on 2026-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playerachievement_media_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public'),
        ),
    ]
