# Generated by Django 6.0 on 2026-07-28 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-created_at'], 'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='playerregistration',
            options={'ordering': ['-joined_date'], 'verbose_name': 'Jogador Registro', 'verbose_name_plural': 'Jogadores Registados'},
        ),
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='É Público?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(choices=[('gk', 'Guarda-redes'), ('cb', 'Defesa Central'), ('lb', 'Defesa Esquerda'), ('rb', 'Defesa Direita'), ('lwb', 'Lateral Esquerda'), ('rwb', 'Lateral Direita'), ('cm', 'Meio-Campo'), ('cdm', 'Meio-Campo Defensivo'), ('cam', 'Meio-Campo Ofensivo'), ('lm', 'Meio-Campo Esquerda'), ('rm', 'Meio-Campo Direito'), ('lw', 'Atacante Esquerda'), ('rw', 'Atacante Direito'), ('st', 'Avançado'), ('cf', 'Centro-avante'), ('multiple', 'Varios Posições')], default='multiple', max_length=20, verbose_name='Primary Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Camisa Preferido'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('retired', 'Retiredo'), ('banned', 'Banido'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='Status do Jogador'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_assists',
            field=models.IntegerField(default=0, verbose_name='Total de Assistências'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_goals',
            field=models.IntegerField(default=0, verbose_name='Total de Gols Feitos'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_matches',
            field=models.IntegerField(default=0, verbose_name='Total de Jogos Jogados'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight_kg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='Total de Assistências'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='goals',
            field=models.IntegerField(default=0, verbose_name='Total de Gols Feitos'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='joined_date',
            field=models.DateField(verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='left_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Saída (se transferiuu)'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='matches_played',
            field=models.IntegerField(default=0, verbose_name='Total de Jogos Jogados'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='players.player', verbose_name='Jogador'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='Total de Cartões Vermelho Feitos'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='shirt_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Camiseta'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registrado'), ('loaned', 'Em Loanamento'), ('suspended', 'Suspendido'), ('retired', 'Retirado'), ('transferred', 'Transferido')], default='registered', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Total de Cartões Amarelos Feitos'),
        ),
    ]
