# Generated by Django 6.0 on 2026-08-08 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0002_alter_mediaasset_owner_type_and_more'),
        ('players', '0006_alter_player_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='global_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='Global ID'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='players.player')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
            },
        ),
        migrations.CreateModel(
            name='LegalGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('document_number', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('consent_status', models.CharField(choices=[('pending', 'Pending'), ('given', 'Given'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('consent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_assets.mediaasset')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_guardians', to='players.player')),
            ],
            options={
                'verbose_name': 'Legal Guardian',
                'verbose_name_plural': 'Legal Guardians',
            },
        ),
        migrations.CreateModel(
            name='PlayerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='players.player')),
            ],
            options={
                'verbose_name': 'Player Contact',
                'verbose_name_plural': 'Player Contacts',
            },
        ),
        migrations.CreateModel(
            name='PlayerPrivacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('club', 'Club'), ('organization', 'Organization'), ('agent', 'Agent'), ('private', 'Private')], default='public', max_length=16)),
                ('contact_visibility', models.CharField(choices=[('public', 'Public'), ('club', 'Club'), ('organization', 'Organization'), ('agent', 'Agent'), ('private', 'Private')], default='club', max_length=16)),
                ('contract_visibility', models.CharField(choices=[('public', 'Public'), ('club', 'Club'), ('organization', 'Organization'), ('agent', 'Agent'), ('private', 'Private')], default='club', max_length=16)),
                ('salary_visibility', models.CharField(choices=[('public', 'Public'), ('club', 'Club'), ('organization', 'Organization'), ('agent', 'Agent'), ('private', 'Private')], default='private', max_length=16)),
                ('medical_visibility', models.CharField(choices=[('public', 'Public'), ('club', 'Club'), ('organization', 'Organization'), ('agent', 'Agent'), ('private', 'Private')], default='private', max_length=16)),
                ('documents_visibility', models.CharField(choices=[('public', 'Public'), ('club', 'Club'), ('organization', 'Organization'), ('agent', 'Agent'), ('private', 'Private')], default='club', max_length=16)),
                ('statistics_visibility', models.CharField(choices=[('public', 'Public'), ('club', 'Club'), ('organization', 'Organization'), ('agent', 'Agent'), ('private', 'Private')], default='public', max_length=16)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='players.player')),
            ],
            options={
                'verbose_name': 'Player Privacy Settings',
                'verbose_name_plural': 'Player Privacy Settings',
            },
        ),
        migrations.CreateModel(
            name='PlayerExternalId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=128)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='players.player')),
            ],
            options={
                'verbose_name': 'Player External ID',
                'verbose_name_plural': 'Player External IDs',
                'indexes': [models.Index(fields=['system', 'external_id'], name='players_pla_system_79c759_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerIdentityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('birth_certificate', 'Birth Certificate'), ('residence_permit', 'Residence Permit'), ('other', 'Other')], max_length=32)),
                ('document_number', models.CharField(max_length=128)),
                ('issuing_country', models.CharField(blank=True, max_length=3, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('document_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_assets.mediaasset')),
                ('document_front', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_assets.mediaasset')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='players.player')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Identity Document',
                'verbose_name_plural': 'Player Identity Documents',
                'indexes': [models.Index(fields=['document_number'], name='players_pla_documen_5f80f5_idx')],
            },
        ),
    ]
