# Generated by Django 6.0 on 2026-08-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_global_id_emergencycontact_legalguardian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='global_id',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='Global ID'),
        ),
    ]
