# Generated by Django 6.0 on 2026-08-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0002_alter_mediaasset_owner_type_and_more'),
        ('players', '0008_alter_player_global_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_profile_photo', to='media_assets.mediaasset', verbose_name='Profile Photo'),
        ),
    ]
