# Generated by Django 6.0 on 2026-08-10 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_clubaffiliationrequest_status'),
        ('competitions', '0018_alter_lineupsubmission_status'),
        ('players', '0009_player_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCareer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('season', models.CharField(blank=True, max_length=32, null=True, verbose_name='Season')),
                ('position', models.CharField(blank=True, max_length=20, null=True, verbose_name='Position')),
                ('appearances', models.IntegerField(default=0, verbose_name='Appearances')),
                ('starts', models.IntegerField(default=0, verbose_name='Starts')),
                ('minutes_played', models.IntegerField(default=0, verbose_name='Minutes Played')),
                ('goals', models.IntegerField(default=0, verbose_name='Goals')),
                ('assists', models.IntegerField(default=0, verbose_name='Assists')),
                ('yellow_cards', models.IntegerField(default=0, verbose_name='Yellow Cards')),
                ('red_cards', models.IntegerField(default=0, verbose_name='Red Cards')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_careers', to='clubs.club', verbose_name='Club')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_careers', to='competitions.competition', verbose_name='Competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='players.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Player Career',
                'verbose_name_plural': 'Player Careers',
                'ordering': ['-season', '-appearances'],
                'unique_together': {('player', 'club', 'season', 'competition')},
            },
        ),
    ]
