# Generated by Django 6.0 on 2026-08-10 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_clubaffiliationrequest_status'),
        ('competitions', '0018_alter_lineupsubmission_status'),
        ('players', '0010_playercareer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFootballProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('primary_position', models.CharField(blank=True, max_length=20, null=True, verbose_name='Primary Position')),
                ('shirt_number', models.IntegerField(blank=True, null=True, verbose_name='Shirt Number')),
                ('height_cm', models.IntegerField(blank=True, null=True, verbose_name='Height (cm)')),
                ('weight_kg', models.IntegerField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('foot', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], max_length=10, null=True, verbose_name='Preferred Foot')),
                ('total_matches', models.IntegerField(default=0, verbose_name='Total Matches')),
                ('total_goals', models.IntegerField(default=0, verbose_name='Total Goals')),
                ('total_assists', models.IntegerField(default=0, verbose_name='Total Assists')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='football_profile', to='players.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Football Profile',
                'verbose_name_plural': 'Football Profiles',
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('season', models.CharField(blank=True, max_length=32, null=True, verbose_name='Season')),
                ('appearances', models.IntegerField(default=0, verbose_name='Appearances')),
                ('starts', models.IntegerField(default=0, verbose_name='Starts')),
                ('minutes', models.IntegerField(default=0, verbose_name='Minutes Played')),
                ('goals', models.IntegerField(default=0, verbose_name='Goals')),
                ('assists', models.IntegerField(default=0, verbose_name='Assists')),
                ('shots', models.IntegerField(default=0, verbose_name='Shots')),
                ('shots_on_target', models.IntegerField(default=0, verbose_name='Shots on Target')),
                ('yellow_cards', models.IntegerField(default=0, verbose_name='Yellow Cards')),
                ('red_cards', models.IntegerField(default=0, verbose_name='Red Cards')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_season_statistics', to='clubs.club', verbose_name='Club')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_season_statistics', to='competitions.competition', verbose_name='Competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_statistics', to='players.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Player Season Statistics',
                'verbose_name_plural': 'Player Season Statistics',
                'ordering': ['-season', '-appearances'],
                'unique_together': {('player', 'club', 'season', 'competition')},
            },
        ),
    ]
