# Generated by Django 6.0 on 2026-08-10 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_playerfootballprofile_playerseasonstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerOnboardingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('account_complete', models.BooleanField(default=False)),
                ('identity_complete', models.BooleanField(default=False)),
                ('personal_complete', models.BooleanField(default=False)),
                ('football_complete', models.BooleanField(default=False)),
                ('contact_complete', models.BooleanField(default=False)),
                ('guardian_complete', models.BooleanField(default=False)),
                ('documents_complete', models.BooleanField(default=False)),
                ('club_complete', models.BooleanField(default=False)),
                ('review_complete', models.BooleanField(default=False)),
                ('current_step', models.CharField(choices=[('account', 'Account Setup'), ('identity', 'Identity & Documents'), ('personal', 'Personal Information'), ('football', 'Football Profile'), ('contact', 'Contact Information'), ('guardian', 'Guardian (if Minor)'), ('documents', 'Supporting Documents'), ('club', 'Club Registration'), ('review', 'Final Review')], default='account', max_length=50, verbose_name='Current Step')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to='players.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Player Onboarding Status',
                'verbose_name_plural': 'Player Onboarding Statuses',
            },
        ),
    ]
