# Generated by Django 6.0 on 2026-08-11 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_clubaffiliationrequest_status'),
        ('core', '0006_remove_tenant_banner_remove_tenant_logo'),
        ('media_assets', '0002_alter_mediaasset_owner_type_and_more'),
        ('players', '0013_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Agente')),
                ('agency_name', models.CharField(blank=True, max_length=255, verbose_name='Nome da Agência')),
                ('agency_type', models.CharField(choices=[('individual', 'Individual Freelancer'), ('agency', 'Sports Agency'), ('firm', 'Law Firm')], default='individual', max_length=20, verbose_name='Tipo de Agência')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Licença')),
                ('fifa_agent_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='ID FIFA Connect')),
                ('country', models.CharField(max_length=3, verbose_name='País')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Verificação')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['fifa_agent_id'], name='players_age_fifa_ag_43691b_idx'), models.Index(fields=['country'], name='players_age_country_f6e154_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerAgentRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('expired', 'Expirado'), ('terminated', 'Terminado'), ('suspended', 'Suspenso')], default='active', max_length=20, verbose_name='Estado')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de Comissão (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_relationships', to='players.agent', verbose_name='Agente')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_relationships', to='players.player', verbose_name='Jogador')),
                ('representation_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_agent_relationships', to='media_assets.mediaasset', verbose_name='Documento de Acordo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_agent_relationships', to='core.tenant', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Representação do Jogador',
                'verbose_name_plural': 'Representações de Jogadores',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('player', 'agent'), name='unique_active_agent_per_player')],
            },
        ),
        migrations.CreateModel(
            name='PlayerContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('contract_type', models.CharField(choices=[('professional', 'Profissional'), ('youth', 'Juniores'), ('amateur', 'Amador'), ('short_term', 'Curto Prazo'), ('trial', 'Período de Teste'), ('loan', 'Empréstimo'), ('extension', 'Renovação')], default='professional', max_length=20, verbose_name='Tipo de Contrato')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('expired', 'Expirado'), ('terminated', 'Terminado'), ('suspended', 'Suspenso')], default='draft', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('signed_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salário')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moeda')),
                ('bonuses', models.JSONField(blank=True, default=dict, help_text="Estrutura: {'appearance': 500, 'goal': 1000, 'win': 2000}", verbose_name='Bónus')),
                ('release_clause', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cláusula de Rescisão')),
                ('has_image_rights', models.BooleanField(default=False, verbose_name='Direitos de Imagem')),
                ('option_year', models.BooleanField(default=False, verbose_name='Opção de Renovação')),
                ('termination_clause', models.TextField(blank=True, verbose_name='Cláusula de Rescisão')),
                ('signed_by_player', models.BooleanField(default=False, verbose_name='Assinado por Jogador')),
                ('signed_by_club', models.BooleanField(default=False, verbose_name='Assinado por Clube')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Verificação')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_contracts', to='clubs.club', verbose_name='Clube')),
                ('contract_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_contracts', to='media_assets.mediaasset', verbose_name='Documento do Contrato')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='players.player', verbose_name='Jogador')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_contracts', to='core.tenant', verbose_name='Organização')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_player_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por')),
            ],
            options={
                'verbose_name': 'Contrato do Jogador',
                'verbose_name_plural': 'Contratos de Jogadores',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'draft'])), fields=('player', 'club', 'start_date'), name='unique_active_contract_per_player_club')],
            },
        ),
        migrations.CreateModel(
            name='PlayerTrainingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academy_name', models.CharField(blank=True, help_text='Se não for um clube registado no sistema', max_length=255, verbose_name='Nome da Academia')),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-3', max_length=3, verbose_name='País')),
                ('training_category', models.CharField(choices=[('amateur', 'Amador'), ('youth', 'Futebol de Base'), ('academy', 'Academia'), ('professional', 'Profissional')], default='amateur', max_length=20, verbose_name='Categoria de Treino')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Verificação')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_training_history', to='clubs.club', verbose_name='Clube')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_history', to='players.player', verbose_name='Jogador')),
                ('training_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_training_certificates', to='media_assets.mediaasset', verbose_name='Certificado')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_player_training_history', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por')),
            ],
            options={
                'verbose_name': 'Historial de Treino do Jogador',
                'verbose_name_plural': 'Historials de Treino do Jogador',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['player', 'start_date'], name='players_pla_player__c92a94_idx'), models.Index(fields=['country', 'training_category'], name='players_pla_country_3c8c90_idx')],
            },
        ),
    ]
