# Generated by Django 6.0 on 2026-08-12 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_alter_lineupsubmission_status'),
        ('media_assets', '0002_alter_mediaasset_owner_type_and_more'),
        ('players', '0014_phase3_professional_models'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('document_type', models.CharField(choices=[('medical_certificate', 'Certificado Médico'), ('injury_report', 'Relatório de Lesão'), ('scan_result', 'Resultado de Exame'), ('lab_result', 'Resultado Laboratorial'), ('vaccination_record', 'Registo de Vacinação'), ('surgery_report', 'Relatório de Cirurgia'), ('physical_exam', 'Exame Físico'), ('cardiac_screening', 'Rastreio Cardíaco'), ('other', 'Outro')], default='other', max_length=30, verbose_name='Tipo de Documento')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('issued_at', models.DateField(verbose_name='Data de Emissão')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('verification_status', models.CharField(choices=[('pending', 'Pendente'), ('verified', 'Verificado'), ('rejected', 'Rejeitado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado de Verificação')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Verificação')),
                ('is_confidential', models.BooleanField(default=True, help_text='Se verdadeiro, apenas pessoal médico autorizado pode aceder', verbose_name='Confidencial')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_documents', to='media_assets.mediaasset', verbose_name='Ficheiro')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='players.player', verbose_name='Jogador')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_medical_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por')),
            ],
            options={
                'verbose_name': 'Documento Médico',
                'verbose_name_plural': 'Documentos Médicos',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMedicalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Desconhecido')], default='unknown', max_length=10, verbose_name='Tipo Sanguíneo')),
                ('medical_status', models.CharField(choices=[('fit', 'Apto'), ('injured', 'Lesionado'), ('recovering', 'Em Recuperação'), ('suspended_medical', 'Suspenso (Médico)')], default='fit', max_length=20, verbose_name='Estado Médico')),
                ('injury_status', models.TextField(blank=True, help_text='Descrição detalhada da lesão atual, se aplicável', verbose_name='Estado da Lesão')),
                ('medical_clearance', models.BooleanField(default=False, help_text='Se o jogador está medicamente apto para competir', verbose_name='Aptidão Médica')),
                ('fitness_status', models.CharField(blank=True, help_text='Avaliação geral da condição física', max_length=255, verbose_name='Estado Físico')),
                ('medical_notes', models.TextField(blank=True, help_text='Observações médicas confidenciais (acesso restrito)', verbose_name='Notas Médicas')),
                ('last_medical_exam', models.DateField(blank=True, null=True, verbose_name='Último Exame Médico')),
                ('next_medical_exam', models.DateField(blank=True, null=True, verbose_name='Próximo Exame Médico')),
                ('allergies', models.TextField(blank=True, help_text='Lista de alergias conhecidas', verbose_name='Alergias')),
                ('current_medications', models.TextField(blank=True, help_text='Medicamentos em uso', verbose_name='Medicamentos Atuais')),
                ('medical_conditions', models.TextField(blank=True, help_text='Condições médicas pré-existentes', verbose_name='Condições Médicas')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='players.player', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Perfil Médico do Jogador',
                'verbose_name_plural': 'Perfis Médicos de Jogadores',
            },
        ),
        migrations.CreateModel(
            name='NationalTeamCallUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('national_team', models.CharField(help_text='Código ISO 3166-1 alpha-3 do país', max_length=3, verbose_name='Seleção Nacional')),
                ('category', models.CharField(choices=[('senior', 'Seleção Principal'), ('u23', 'Sub-23'), ('u20', 'Sub-20'), ('u17', 'Sub-17'), ('u15', 'Sub-15')], default='senior', max_length=20, verbose_name='Categoria')),
                ('call_up_date', models.DateField(verbose_name='Data de Convocatória')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Libertação')),
                ('status', models.CharField(choices=[('called', 'Convocado'), ('released', 'Libertado'), ('declined', 'Recusou'), ('injured', 'Lesionado'), ('completed', 'Concluído')], default='called', max_length=20, verbose_name='Estado')),
                ('caps', models.IntegerField(default=0, help_text='Número de jogos disputados pela seleção', verbose_name='Internacionalizações')),
                ('goals', models.IntegerField(default=0, help_text='Golos marcados pela seleção', verbose_name='Golos')),
                ('assists', models.IntegerField(default=0, help_text='Assistências pela seleção', verbose_name='Assistências')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_team_call_ups', to='competitions.competition', verbose_name='Competição')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_team_call_ups', to='players.player', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Convocatória de Seleção',
                'verbose_name_plural': 'Convocatórias de Seleção',
                'ordering': ['-call_up_date'],
                'indexes': [models.Index(fields=['player', 'call_up_date'], name='players_nat_player__02053a_idx'), models.Index(fields=['national_team', 'category'], name='players_nat_nationa_3c9950_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerComplianceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rule_type', models.CharField(choices=[('minor_transfer', 'Transferência de Menor'), ('international_transfer', 'Transferência Internacional'), ('first_registration', 'Primeiro Registo'), ('work_permit', 'Autorização de Trabalho'), ('visa', 'Visto'), ('passport_validity', 'Validade do Passaporte'), ('training_compensation', 'Compensação de Formação'), ('solidarity_contribution', 'Contribuição de Solidariedade'), ('contract_length', 'Duração do Contrato'), ('contract_stability', 'Estabilidade Contratual'), ('registration_window', 'Janela de Registo'), ('other', 'Outro')], max_length=30, verbose_name='Tipo de Regra')),
                ('rule_reference', models.CharField(blank=True, help_text='Ex: RSTP Art. 19, Ann. 4, etc.', max_length=50, verbose_name='Referência da Regra')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('compliant', 'Conforme'), ('non_compliant', 'Não Conforme'), ('pending_review', 'Em Revisão'), ('exemption_granted', 'Isenção Concedida'), ('requires_approval', 'Requer Aprovação')], default='pending_review', max_length=20, verbose_name='Estado de Conformidade')),
                ('description', models.TextField(help_text='Descrição do requisito de conformidade', verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, help_text='Observações adicionais sobre o estado de conformidade', verbose_name='Notas')),
                ('resolution_notes', models.TextField(blank=True, help_text='Como a questão de conformidade foi ou deve ser resolvida', verbose_name='Notas de Resolução')),
                ('exemption_reason', models.TextField(blank=True, help_text='Se isenção foi concedida, justificação', verbose_name='Motivo da Isenção')),
                ('deadline', models.DateField(blank=True, help_text='Prazo para resolução', null=True, verbose_name='Prazo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Revisão')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='players.player', verbose_name='Jogador')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_compliance_records', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='compliance_records', to='media_assets.mediaasset', verbose_name='Documentos de Suporte')),
                ('transfer', models.ForeignKey(blank=True, help_text='Transferência associada, se aplicável', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_records', to='transfers.transfer', verbose_name='Transferência')),
            ],
            options={
                'verbose_name': 'Registo de Conformidade',
                'verbose_name_plural': 'Registos de Conformidade',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['player', 'status'], name='players_pla_player__b80247_idx'), models.Index(fields=['rule_type'], name='players_pla_rule_ty_f3c755_idx'), models.Index(fields=['deadline'], name='players_pla_deadlin_724c13_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerPerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('recorded_at', models.DateTimeField(verbose_name='Data de Registo')),
                ('metric_type', models.CharField(choices=[('max_speed', 'Velocidade Máxima (km/h)'), ('avg_speed', 'Velocidade Média (km/h)'), ('sprint_speed', 'Velocidade de Sprint (km/h)'), ('total_distance', 'Distância Total (m)'), ('sprint_distance', 'Distância em Sprint (m)'), ('high_speed_distance', 'Distância Alta Velocidade (m)'), ('sprints_count', 'Número de Sprints'), ('accelerations', 'Acelerações'), ('decelerations', 'Desacelerações'), ('jumps', 'Saltos'), ('max_heart_rate', 'Frequência Cardíaca Máxima (bpm)'), ('avg_heart_rate', 'Frequência Cardíaca Média (bpm)'), ('heart_rate_zones', 'Tempo por Zonas Cardíacas'), ('player_load', 'Carga de Trabalho'), ('training_load', 'Carga de Treino'), ('match_load', 'Carga de Jogo'), ('recovery_time', 'Tempo de Recuperação (h)'), ('fatigue_index', 'Índice de Fadiga'), ('other', 'Outro')], max_length=30, verbose_name='Tipo de Métrica')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('unit', models.CharField(help_text='Ex: km/h, m, bpm, etc.', max_length=20, verbose_name='Unidade')),
                ('source', models.CharField(choices=[('gps', 'Dispositivo GPS'), ('wearable', 'Dispositivo Vestível'), ('manual', 'Registo Manual'), ('video_analysis', 'Análise de Vídeo'), ('club_system', 'Sistema do Clube'), ('other', 'Outro')], default='gps', max_length=20, verbose_name='Fonte')),
                ('device_id', models.CharField(blank=True, help_text='Identificador do dispositivo que capturou a métrica', max_length=100, verbose_name='ID do Dispositivo')),
                ('training_session', models.CharField(blank=True, help_text='Identificador da sessão de treino, se aplicável', max_length=255, verbose_name='Sessão de Treino')),
                ('position_during_metric', models.CharField(blank=True, help_text='Posição do jogador quando a métrica foi registada', max_length=20, verbose_name='Posição Durante Métrica')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Dados estruturados adicionais (ex: zonas cardíacas, distribuição de velocidade)', verbose_name='Dados Adicionais')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('match', models.ForeignKey(blank=True, help_text='Se aplicável, o jogo associado a esta métrica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_performance_metrics', to='competitions.match', verbose_name='Jogo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='players.player', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Métrica de Performance',
                'verbose_name_plural': 'Métricas de Performance',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['player', 'recorded_at'], name='players_pla_player__202ce5_idx'), models.Index(fields=['metric_type'], name='players_pla_metric__297d8e_idx'), models.Index(fields=['match'], name='players_pla_match_i_c7704c_idx')],
            },
        ),
    ]
