# Generated by Codex on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0015_phase4_ecosystem_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerregistrationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("invited", "Convidado"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerregistrationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("competition__isnull", True),
                    ("status", "pending"),
                ),
                fields=("player", "club"),
                name="unique_pending_player_club_without_competition",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerregistrationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("competition__isnull", False),
                    ("status", "pending"),
                ),
                fields=("player", "club", "competition"),
                name="unique_pending_player_club_competition",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerregistrationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("competition__isnull", True),
                    ("status", "invited"),
                ),
                fields=("player", "club"),
                name="unique_invited_player_club_without_competition",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerregistrationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("competition__isnull", False),
                    ("status", "invited"),
                ),
                fields=("player", "club", "competition"),
                name="unique_invited_player_club_competition",
            ),
        ),
    ]
