# Generated by Antigravity on 2026-09-07

from django.db import migrations, models


def update_accepted_status(apps, schema_editor):
    PlayerRegistrationRequest = apps.get_model("players", "PlayerRegistrationRequest")
    PlayerRegistrationRequest.objects.filter(registration__isnull=False).update(status="accepted")


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0016_playerregistrationrequest_state_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerregistrationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("invited", "Convidado"),
                    ("approved", "Aprovado pelo Clube"),
                    ("accepted", "Aceito"),
                    ("rejected", "Rejeitado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.RunPython(update_accepted_status, reverse_code=migrations.RunPython.noop),
    ]
