# Generated by Django 5.1.7 on 2026-09-19 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0012_club_gender"),
        ("core", "0006_remove_tenant_banner_remove_tenant_logo"),
        ("players", "0017_playerregistrationrequest_accepted_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="gender",
            field=models.CharField(
                choices=[("male", "Masculino"), ("female", "Feminino")],
                default="male",
                max_length=10,
                verbose_name="Género",
            ),
        ),
        migrations.CreateModel(
            name="PlayerCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("federation", "Federação"), ("club", "Clube")],
                        default="federation",
                        max_length=20,
                        verbose_name="Âmbito",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome da Categoria"),
                ),
                ("slug", models.SlugField(max_length=100, verbose_name="Slug")),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Idade Mínima"
                    ),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Idade Máxima"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Masculino"),
                            ("female", "Feminino"),
                            ("mixed", "Misto"),
                        ],
                        default="mixed",
                        max_length=10,
                        verbose_name="Género Elegível",
                    ),
                ),
                (
                    "is_custom",
                    models.BooleanField(default=False, verbose_name="É Personalizada?"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preenchido quando a categoria é personalizada pelo clube.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_categories",
                        to="clubs.club",
                        verbose_name="Clube",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_categories",
                        to="core.tenant",
                        verbose_name="Organização / Federação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Jogador",
                "verbose_name_plural": "Categorias de Jogadores",
                "ordering": ["display_order", "min_age", "name"],
            },
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="players.playercategory",
                verbose_name="Categoria / Escalão",
            ),
        ),
        migrations.AddConstraint(
            model_name="playercategory",
            constraint=models.UniqueConstraint(
                fields=("tenant", "club", "slug"),
                name="unique_category_slug_per_tenant_club",
            ),
        ),
    ]
